import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Alert, Box, Button, Chip, FormControl, InputLabel, MenuItem, Paper, Select, Stack, Typography } from "@mui/material";
import { CheckCircle2, Cpu, Database, Layers3 } from "lucide-react";
import { fetchDatasets, fetchDatasetPreview } from "../platform/platformApi";

interface Props { moduleKey:string; title:string; description:string; resourceClass:"light"|"medium"|"heavy"; capabilities:string[]; }
export function CapabilityModulePanel({ moduleKey,title,description,resourceClass,capabilities }:Props){
 const datasets=useQuery({queryKey:["platform","datasets"],queryFn:fetchDatasets}); const [choice,setChoice]=useState(""); const datasetId=choice||datasets.data?.[0]?.dataset_id||""; const preview=useQuery({queryKey:["platform","preview",datasetId],queryFn:()=>fetchDatasetPreview(datasetId),enabled:Boolean(datasetId)});
 return <Stack spacing={2.5}><Paper className="feature-hero" variant="outlined" sx={{p:{xs:2.5,md:4}}}><Stack direction={{xs:"column",md:"row"}} spacing={2} justifyContent="space-between"><Box><Stack direction="row" spacing={1} alignItems="center"><Layers3 size={22}/><Typography variant="overline">Intelligence module</Typography></Stack><Typography variant="h4" mt={1}>{title}</Typography><Typography mt={1} maxWidth={820}>{description}</Typography></Box><Chip icon={<Cpu size={16}/>} label={`${resourceClass} resource class`} sx={{alignSelf:"flex-start",bgcolor:"rgba(255,255,255,.16)",color:"white"}}/></Stack></Paper>
 <Paper variant="outlined" sx={{p:2.5,bgcolor:"#fff",opacity:1}}><Stack direction={{xs:"column",md:"row"}} spacing={2} alignItems={{md:"center"}}><Database/><Box flex={1}><Typography variant="h6">Dataset context</Typography><Typography color="text.secondary">Bind the module to an uploaded dataset so its capability boundary is grounded in real project data.</Typography></Box><FormControl sx={{minWidth:300}}><InputLabel>Dataset</InputLabel><Select label="Dataset" value={datasetId} onChange={e=>setChoice(e.target.value)}>{(datasets.data??[]).map(d=><MenuItem key={d.dataset_id} value={d.dataset_id}>{d.name}</MenuItem>)}</Select></FormControl></Stack>{preview.data&&<Stack direction="row" gap={1} flexWrap="wrap" mt={2}><Chip label={`${preview.data.total_rows} rows`}/><Chip label={`${preview.data.columns.length} columns`}/>{preview.data.columns.slice(0,8).map(c=><Chip key={c} size="small" variant="outlined" label={c}/>)}</Stack>}{!datasetId&&<Alert severity="info" sx={{mt:2}}>Upload a dataset first to activate this module context.</Alert>}</Paper>
 <Box display="grid" gridTemplateColumns={{xs:"1fr",sm:"repeat(2,1fr)",lg:"repeat(3,1fr)"}} gap={2}>{capabilities.map(capability=><Paper className="module-card" key={capability} variant="outlined" sx={{p:2.25,bgcolor:"#fff",opacity:1}}><Stack direction="row" spacing={1.25} alignItems="center"><CheckCircle2 size={18} color="#087f5b"/><Typography fontWeight={700}>{capability}</Typography></Stack><Typography variant="body2" color="text.secondary" mt={1}>{datasetId?`Ready to operate on ${preview.data?.total_rows??"the selected"} dataset records.`:"Waiting for dataset selection."}</Typography></Paper>)}</Box>
 <Alert severity="info">Module key: <b>{moduleKey}</b>. Capabilities that have dedicated runtime services open directly as full workspaces. This panel provides live dataset binding for the remaining registered capability boundaries.</Alert></Stack>
}
