import {useEffect,useMemo,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {Alert,Button,Checkbox,Dialog,DialogActions,DialogContent,DialogTitle,FormControl,FormControlLabel,Grid,InputLabel,MenuItem,Paper,Select,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,Tooltip,Typography} from "@mui/material";
import {ChevronLeft,ChevronRight,Clipboard,Download,Plus,Save,ShieldCheck,Trash2} from "lucide-react";
import {downloadDatasetFile,editDataset,fetchDatasetPreview,fetchDatasetQuality,prepareDataset,type DatasetPreview,type DatasetSummary} from "./platformApi";

const PAGE_SIZE=40;
const timestamp=()=>new Date().toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/,"Z");

export function DataPreparationStudio({datasetId,datasets,onSelect}:{datasetId:string;datasets:DatasetSummary[];onSelect:(id:string)=>void}){
 const qc=useQueryClient(); const [rows,setRows]=useState<Record<string,unknown>[]>([]); const [selected,setSelected]=useState<{row:number;column:string}|null>(null); const [page,setPage]=useState(0);
 const [nulls,setNulls]=useState("-999.25, -999, -9999, -99999, 999.25, 9999"); const [zeroCols,setZeroCols]=useState(""); const [depth,setDepth]=useState("");
 const [scaling,setScaling]=useState<"none"|"standard"|"minmax"|"robust">("none"); const [scaleCols,setScaleCols]=useState(""); const [despike,setDespike]=useState(true); const [smooth,setSmooth]=useState(false); const [clip,setClip]=useState(false);
 const [ops,setOps]=useState<Array<Record<string,unknown>>>([]); const [rename,setRename]=useState<{column:string;name:string}|null>(null); const [newColumn,setNewColumn]=useState(""); const [formula,setFormula]=useState("");
 const preview=useQuery<DatasetPreview>({queryKey:["prep-preview",datasetId],queryFn:()=>fetchDatasetPreview(datasetId,120),enabled:Boolean(datasetId),staleTime:60000});
 const quality=useQuery({queryKey:["prep-quality",datasetId],queryFn:()=>fetchDatasetQuality(datasetId),enabled:Boolean(datasetId),staleTime:60000});
 useEffect(()=>{setRows(preview.data?.rows.map(r=>({...r}))??[]);setOps([]);setPage(0);setSelected(null)},[preview.data]);
 const columns=preview.data?.columns??[]; const current=datasets.find(d=>d.dataset_id===datasetId); const pageCount=Math.max(1,Math.ceil(rows.length/PAGE_SIZE));
 const visibleRows=useMemo(()=>rows.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE),[rows,page]);
 const save=useMutation({mutationFn:()=>editDataset(datasetId,{name:`${current?.name??"Dataset"} · edited · ${timestamp()}`,operations:ops}),onSuccess:async d=>{await qc.invalidateQueries({queryKey:["platform","datasets"]});onSelect(d.dataset_id)}});
 const prepare=useMutation({mutationFn:()=>prepareDataset(datasetId,{name:`${current?.name??"Dataset"} · ML-ready · ${timestamp()}`,null_values:nulls.split(",").map(Number).filter(Number.isFinite),zero_as_null_columns:zeroCols.split(",").map(x=>x.trim()).filter(Boolean),depth_column:depth||null,interpolate_limit:3,despike,smooth,clip_physical_ranges:clip,scaling,scaling_columns:scaleCols.split(",").map(x=>x.trim()).filter(Boolean)}),onSuccess:async d=>{await Promise.all([qc.invalidateQueries({queryKey:["platform","datasets"]}),qc.invalidateQueries({queryKey:["dataset-preview"]}),qc.invalidateQueries({queryKey:["prep-preview"]}),qc.invalidateQueries({queryKey:["prep-quality"]})]);onSelect(d.dataset_id)}});
 function setCell(row:number,column:string,value:string){setRows(v=>v.map((r,i)=>i===row?{...r,[column]:value}:r));setOps(v=>[...v,{action:"set_cell",row,column,value}])}
 async function paste(){if(!selected)return;const value=await navigator.clipboard.readText();setCell(selected.row,selected.column,value)}
 async function copy(){if(!selected)return;await navigator.clipboard.writeText(String(rows[selected.row]?.[selected.column]??""))}
 return <Stack spacing={2}>
  <Paper variant="outlined" sx={{p:2}}><Grid container spacing={2} alignItems="center"><Grid item xs={12} md={5}><FormControl fullWidth><InputLabel>Dataset to inspect</InputLabel><Select label="Dataset to inspect" value={datasetId} onChange={e=>onSelect(e.target.value)}>{datasets.map(d=><MenuItem key={d.dataset_id} value={d.dataset_id}>{d.name} · {d.row_count??0} rows</MenuItem>)}</Select></FormControl></Grid><Grid item xs={12} md={7}><Stack direction="row" gap={1} flexWrap="wrap"><Button startIcon={<Clipboard size={15}/>} onClick={copy} disabled={!selected}>Copy</Button><Button startIcon={<Clipboard size={15}/>} onClick={paste} disabled={!selected}>Paste</Button><Button startIcon={<Plus size={15}/>} onClick={()=>setNewColumn("new_column")}>Add column</Button><Button startIcon={<Plus size={15}/>} onClick={()=>{setRows(v=>[...v,{}]);setOps(v=>[...v,{action:"add_row",values:{}}]);setPage(Math.floor(rows.length/PAGE_SIZE))}}>Add row</Button><Button startIcon={<Save size={15}/>} variant="contained" onClick={()=>save.mutate()} disabled={!ops.length||save.isPending}>Save edited copy</Button><Button startIcon={<Download size={15}/>} onClick={()=>current&&downloadDatasetFile(datasetId,current.file_name)}>Download dataset</Button></Stack></Grid></Grid></Paper>
  {(quality.data?.unit_warnings.length??0)>0&&<Alert severity="warning"><b>Unit review:</b> missing units are flagged but do not block the workflow.<Stack mt={1}>{quality.data!.unit_warnings.map(w=><span key={w}>• {w}</span>)}</Stack></Alert>}
  {(quality.data?.warnings.length??0)>0&&<Alert severity="info">{quality.data!.warnings.join(" ")}</Alert>}
  <Grid container spacing={2}><Grid item xs={12} lg={8}><TableContainer component={Paper} variant="outlined" sx={{maxHeight:520}}><Table stickyHeader size="small"><TableHead><TableRow><TableCell>#</TableCell>{columns.map(c=><TableCell key={c} sx={{minWidth:130,fontWeight:800}}><Stack direction="row" alignItems="center">{c}<Tooltip title="Rename"><Button size="small" onClick={()=>setRename({column:c,name:c})}>✎</Button></Tooltip><Tooltip title="Delete column"><Button color="error" size="small" onClick={()=>setOps(v=>[...v,{action:"delete_column",column:c}])}><Trash2 size={13}/></Button></Tooltip></Stack></TableCell>)}</TableRow></TableHead><TableBody>{visibleRows.map((r,localIndex)=>{const i=page*PAGE_SIZE+localIndex;return <TableRow key={i} hover selected={selected?.row===i}><TableCell><Button color="error" size="small" onClick={()=>{setRows(v=>v.filter((_,n)=>n!==i));setOps(v=>[...v,{action:"delete_row",row:i}])}}><Trash2 size={13}/></Button>{i+1}</TableCell>{columns.map(c=><TableCell key={c} onClick={()=>setSelected({row:i,column:c})} sx={{p:.5}}><input aria-label={`${c} row ${i+1}`} value={String(r[c]??"")} onChange={e=>setCell(i,c,e.target.value)} style={{width:"100%",minWidth:105,border:"none",outline:"none",background:"transparent",color:"inherit",font:"inherit",padding:"6px"}}/></TableCell>)}</TableRow>})}</TableBody></Table></TableContainer><Stack direction="row" justifyContent="space-between" alignItems="center" mt={1}><Typography variant="caption" color="text.secondary">Showing {rows.length?`${page*PAGE_SIZE+1}–${Math.min((page+1)*PAGE_SIZE,rows.length)}`:"0"} of {rows.length} preview rows. The server loads at most 120 rows to protect browser memory.</Typography><Stack direction="row" alignItems="center"><Button size="small" startIcon={<ChevronLeft size={14}/>} disabled={page===0} onClick={()=>setPage(v=>v-1)}>Previous</Button><Typography variant="caption">Page {page+1}/{pageCount}</Typography><Button size="small" endIcon={<ChevronRight size={14}/>} disabled={page>=pageCount-1} onClick={()=>setPage(v=>v+1)}>Next</Button></Stack></Stack></Grid>
  <Grid item xs={12} lg={4}><Paper variant="outlined" sx={{p:2}}><Stack spacing={1.5}><Typography variant="h6">Petroleum ML preparation</Typography><TextField label="Null markers" value={nulls} onChange={e=>setNulls(e.target.value)} helperText="0 is never treated as null globally."/><TextField label="Columns where zero means missing" value={zeroCols} onChange={e=>setZeroCols(e.target.value)} helperText="Optional, comma-separated."/><TextField select label="Depth/time column" value={depth} onChange={e=>setDepth(e.target.value)}><MenuItem value="">Auto-detect</MenuItem>{columns.map(c=><MenuItem key={c} value={c}>{c}</MenuItem>)}</TextField><FormControl><InputLabel>Scaling</InputLabel><Select label="Scaling" value={scaling} onChange={e=>setScaling(e.target.value as typeof scaling)}><MenuItem value="none">None / model-aware training pipeline</MenuItem><MenuItem value="standard">Standardisation</MenuItem><MenuItem value="minmax">Min-max normalisation</MenuItem><MenuItem value="robust">Robust scaling</MenuItem></Select></FormControl><TextField label="Columns to scale" value={scaleCols} onChange={e=>setScaleCols(e.target.value)} helperText="Blank means all numeric logs except depth."/><FormControlLabel control={<Checkbox checked={despike} onChange={e=>setDespike(e.target.checked)}/>} label="Hampel despiking"/><FormControlLabel control={<Checkbox checked={smooth} onChange={e=>setSmooth(e.target.checked)}/>} label="Optional smoothing"/><FormControlLabel control={<Checkbox checked={clip} onChange={e=>setClip(e.target.checked)}/>} label="Clip to physical ranges"/><Button variant="contained" startIcon={<ShieldCheck/>} onClick={()=>prepare.mutate()} disabled={prepare.isPending}>{prepare.isPending?"Preparing…":"Create ML-ready dataset"}</Button>{prepare.isError&&<Alert severity="error">{prepare.error instanceof Error?prepare.error.message:"Preparation failed"}</Alert>}<Alert severity="success">The created dataset receives a UTC timestamp and becomes the selected source in Train Model and Predict Dataset. Missing units remain warning-only.</Alert></Stack></Paper></Grid></Grid>
  <Dialog open={Boolean(rename)} onClose={()=>setRename(null)}><DialogTitle>Rename column</DialogTitle><DialogContent><TextField autoFocus margin="dense" value={rename?.name??""} onChange={e=>setRename(v=>v?{...v,name:e.target.value}:v)}/></DialogContent><DialogActions><Button onClick={()=>setRename(null)}>Cancel</Button><Button onClick={()=>{if(rename){setOps(v=>[...v,{action:"rename_column",column:rename.column,new_name:rename.name}]);setRename(null)}}}>Apply</Button></DialogActions></Dialog>
  <Dialog open={Boolean(newColumn)} onClose={()=>setNewColumn("")}><DialogTitle>Add derived column</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField label="Column name" value={newColumn} onChange={e=>setNewColumn(e.target.value)}/><TextField label="Formula or leave blank" value={formula} onChange={e=>setFormula(e.target.value)} helperText="Example: 0.5 * (NPHI + PHID)"/></Stack></DialogContent><DialogActions><Button onClick={()=>setNewColumn("")}>Cancel</Button><Button onClick={()=>{setOps(v=>[...v,formula?{action:"formula_column",column:newColumn,expression:formula}:{action:"add_column",column:newColumn,default_value:null}]);setNewColumn("");setFormula("")}}>Add</Button></DialogActions></Dialog>
 </Stack>
}
