import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Alert, Box, Button, Chip, FormControl, Grid, InputLabel, LinearProgress, MenuItem, Paper, Select, Stack, TextField, Typography } from "@mui/material";
import { Bot, Database, Send, Sparkles } from "lucide-react";
import { apiRequest } from "../../api/http";
import { askAssistant, fetchDatasets } from "./platformApi";
type Well={well_id:string;field?:string|null};
export function AiAssistantPanel(){
 const ds=useQuery({queryKey:["platform","datasets"],queryFn:fetchDatasets});
 const wells=useQuery({queryKey:["wells"],queryFn:()=>apiRequest<Well[]>("/wells")});
 const [chosen,setChosen]=useState(""); const id=chosen||(ds.data?.[0]?.dataset_id??""); const selected=ds.data?.find(d=>d.dataset_id===id);
 const availableNames=useMemo(()=>{const names=(wells.data??[]).map(w=>w.well_id).filter(Boolean);return names.length?names:(ds.data??[]).map(d=>d.name);},[wells.data,ds.data]);
 const suggestions=useMemo(()=>["Summarise the selected dataset","Identify the strongest hydrocarbon interval","Which interval has the highest porosity?","Explain the main reservoir-quality risks",availableNames.length>1?`Compare ${availableNames.slice(0,3).join(", ")}`:"Describe the lithology distribution","What additional evidence is needed for a confident interpretation?"],[availableNames]);
 const [question,setQuestion]=useState(""); const m=useMutation({mutationFn:(q:string)=>askAssistant(id,q)}); useEffect(()=>m.reset(),[id]);
 const submit=(q=question)=>{if(id&&q.trim()){setQuestion(q);m.mutate(q.trim());}};
 return <Stack spacing={3}><Paper className="feature-hero" sx={{p:{xs:3,md:4}}}><Stack direction="row" gap={1.2} alignItems="center"><Bot/><Box><Typography variant="h4" fontWeight={900}>Petroleum-domain AI Assistant</Typography><Typography mt={1}>Ask open-ended questions grounded in uploaded datasets, interpreted results, model outputs and petroleum domain knowledge.</Typography></Box></Stack></Paper>
 <Grid container spacing={2}><Grid item xs={12} md={7}><FormControl fullWidth><InputLabel>Dataset under analysis</InputLabel><Select label="Dataset under analysis" value={id} onChange={e=>setChosen(e.target.value)}>{(ds.data??[]).map(d=><MenuItem key={d.dataset_id} value={d.dataset_id}>{d.name}</MenuItem>)}</Select></FormControl></Grid><Grid item xs={12} md={5}><Paper variant="outlined" sx={{p:1.5,height:"100%"}}><Stack direction="row" gap={1} alignItems="center"><Database size={17}/><Typography fontWeight={750}>Available wells/assets</Typography></Stack><Typography variant="body2" color="text.secondary" mt={0.5}>{availableNames.length?availableNames.join(", "):"No wells are currently registered."}</Typography></Paper></Grid></Grid>
 <Stack direction="row" gap={1} flexWrap="wrap">{suggestions.map(q=><Chip key={q} icon={<Sparkles size={14}/>} label={q} onClick={()=>submit(q)} clickable/>)}</Stack>
 <TextField multiline minRows={3} label={`Ask about ${selected?.name??"the selected dataset"}`} value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();submit();}}}/><Button variant="contained" startIcon={<Send/>} onClick={()=>submit()} disabled={!id||!question.trim()||m.isPending}>{m.isPending?"Analysing available evidence…":"Analyse evidence"}</Button>
 {m.isPending&&<LinearProgress/>}{m.isError&&<Alert severity="error">{m.error instanceof Error?m.error.message:"The assistant could not analyse the selected evidence."}</Alert>}
 {m.data&&<Grid container spacing={2}><Grid item xs={12} lg={7}><Paper variant="outlined" sx={{p:3,height:"100%"}}><Typography variant="overline">Intent: {m.data.intent.replace(/_/g," ")}</Typography><Typography variant="h6">PetroEdge response</Typography><Typography mt={1.5}>{m.data.answer}</Typography>{m.data.evidence.length>0?<><Typography variant="subtitle2" mt={2}>Evidence used</Typography>{m.data.evidence.map(x=><Typography key={x}>• {x}</Typography>)}</>:<Alert severity="info" sx={{mt:2}}>The requested answer was not found in the selected dataset or available analyses. PetroEdge will not invent unsupported project-specific facts.</Alert>}</Paper></Grid><Grid item xs={12} lg={5}><Paper variant="outlined" sx={{p:3,height:"100%"}}><Typography variant="h6">Explainable interpretation</Typography><Stack direction="row" gap={1} flexWrap="wrap" mt={1}><Chip color={m.data.explanation.prediction==="Pay"?"success":"default"} label={m.data.explanation.prediction}/><Chip label={`${m.data.explanation.depth.toFixed(2)} m`}/><Chip label={m.data.explanation.lithology}/></Stack><Typography mt={2}>Confidence {(m.data.explanation.confidence*100).toFixed(1)}%</Typography><LinearProgress variant="determinate" value={m.data.explanation.confidence*100} sx={{height:9,borderRadius:5,mt:.5}}/><Typography mt={1}>Porosity {(m.data.explanation.porosity*100).toFixed(1)}% · Sw {(m.data.explanation.water_saturation*100).toFixed(1)}%</Typography><Typography variant="subtitle2" mt={2}>Contributing evidence</Typography>{m.data.explanation.feature_importance.map(item=><Box key={item.feature} mt={1}><Stack direction="row" justifyContent="space-between"><Typography variant="body2">{item.feature}</Typography><Typography variant="body2">{(item.contribution*100).toFixed(1)}%</Typography></Stack><LinearProgress variant="determinate" value={item.contribution*100}/></Box>)}</Paper></Grid></Grid>}
 </Stack>;
}
