import { FormEvent, useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, LinearProgress, Paper, Stack, TextField, Typography } from "@mui/material";
import { Activity, BriefcaseBusiness, Database, FileUp, HardDrive, RefreshCw, Search, Table2, Trash2 } from "lucide-react";
import { navigateTo } from "../../lib/platformNavigation";
import { refreshPlatform } from "../../lib/refresh";
import { deleteDataset, fetchDatasets, uploadDataset, type DatasetSummary } from "./platformApi";

const bytes=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
export function DatasetRegistryPanel(){
 const qc=useQueryClient(); const selectedWell=sessionStorage.getItem("petroedge_selected_well_id"); const [open,setOpen]=useState(false); const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [file,setFile]=useState<File|null>(null); const [search,setSearch]=useState(""); const [selected,setSelected]=useState<DatasetSummary|null>(null); const [deleteTarget,setDeleteTarget]=useState<DatasetSummary|null>(null);
 const query=useQuery({queryKey:["platform","datasets"],queryFn:fetchDatasets});
 const refresh=async()=>refreshPlatform(qc,[["platform"],["platform","datasets"],["wells"],["sprint2","operations"]]);
 const upload=useMutation({mutationFn:()=>uploadDataset(name,description,file!),onSuccess:async()=>{await refresh();setOpen(false);setName("");setDescription("");setFile(null);}});
 const remove=useMutation({mutationFn:(id:string)=>deleteDataset(id),onSuccess:async()=>{await refresh();setDeleteTarget(null);setSelected(null);}});
 const rows=useMemo(()=>(query.data??[]).filter(d=>`${d.name} ${d.file_name} ${d.source_type}`.toLowerCase().includes(search.toLowerCase())),[query.data,search]);
 useEffect(()=>{
  const pendingId=sessionStorage.getItem("petroedge_open_dataset_id");
  if(!pendingId||!query.data)return;
  const dataset=query.data.find(item=>item.dataset_id===pendingId);
  if(dataset){setSelected(dataset);sessionStorage.removeItem("petroedge_open_dataset_id");}
 },[query.data]);
 const submit=(e:FormEvent)=>{e.preventDefault();if(name.trim()&&file)upload.mutate();};
 return <Stack spacing={3}>
  <Stack direction={{xs:"column",md:"row"}} justifyContent="space-between" gap={2}><Box><Stack direction="row" gap={1} alignItems="center"><Database size={24}/><Typography variant="h5">Dataset registry</Typography></Stack><Typography variant="body2" color="text.secondary">Upload, profile, interpret and manage CSV, Parquet and LAS datasets.{selectedWell?` Asset context: ${selectedWell}.`:""}</Typography></Box><Stack direction="row" gap={1} flexWrap="wrap"><Button variant="outlined" startIcon={<BriefcaseBusiness size={17}/>} onClick={()=>navigateTo("Assets")}>Assets</Button><Button variant="outlined" startIcon={<Activity size={17}/>} onClick={()=>navigateTo("Operations")}>Operations</Button><Button variant="outlined" startIcon={<RefreshCw size={17}/>} onClick={()=>void refresh()}>Refresh</Button><Button variant="contained" startIcon={<FileUp size={17}/>} onClick={()=>setOpen(true)}>Upload dataset</Button></Stack></Stack>
  <TextField size="small" placeholder="Search datasets" value={search} onChange={e=>setSearch(e.target.value)} InputProps={{startAdornment:<Search size={17} style={{marginRight:8}}/>}}/>
  {query.isLoading&&<LinearProgress/>}{query.isError&&<Alert severity="error">{query.error instanceof Error?query.error.message:"Unable to load datasets."}</Alert>}
  {!query.isLoading&&rows.length===0&&<Paper variant="outlined" sx={{p:5,textAlign:"center"}}><Database size={42}/><Typography variant="h6" mt={1}>No datasets found</Typography><Typography color="text.secondary">Upload a well-log dataset to begin.</Typography></Paper>}
  <Stack spacing={1.5}>{rows.map(d=><Paper key={d.dataset_id} variant="outlined" sx={{p:2.25,"&:hover":{borderColor:"primary.main"}}}><Stack direction={{xs:"column",md:"row"}} justifyContent="space-between" gap={2}><Box onClick={()=>setSelected(d)} sx={{cursor:"pointer",flex:1}}><Stack direction="row" gap={1} alignItems="center"><Typography variant="h6">{d.name}</Typography><Chip size="small" label={d.source_type.toUpperCase()} color="primary" variant="outlined"/><Chip size="small" label={d.status}/></Stack><Typography variant="body2" color="text.secondary">{d.description||d.file_name}</Typography></Box><Stack direction="row" gap={3} alignItems="center"><Box><Typography variant="caption" color="text.secondary">Rows</Typography><Typography>{d.row_count?.toLocaleString()??"—"}</Typography></Box><Box><Typography variant="caption" color="text.secondary">Columns</Typography><Typography>{d.column_count??"—"}</Typography></Box><Box><Typography variant="caption" color="text.secondary">Size</Typography><Typography>{bytes(d.file_size_bytes)}</Typography></Box><Button variant="outlined" startIcon={<Activity size={16}/>} onClick={()=>navigateTo("Operations",{wellId:selectedWell??undefined,datasetId:d.dataset_id})}>Use in operations</Button><Button color="error" variant="outlined" startIcon={<Trash2 size={16}/>} onClick={()=>setDeleteTarget(d)}>Delete</Button></Stack></Stack></Paper>)}</Stack>
  <Dialog open={open} onClose={()=>!upload.isPending&&setOpen(false)} fullWidth maxWidth="sm"><form onSubmit={submit}><DialogTitle>Register dataset</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField label="Dataset name" required value={name} onChange={e=>setName(e.target.value)}/><TextField label="Description" multiline minRows={2} value={description} onChange={e=>setDescription(e.target.value)}/><Button component="label" variant="outlined" startIcon={<FileUp size={17}/>}>{file?file.name:"Choose CSV, Parquet or LAS"}<input hidden type="file" accept=".csv,.parquet,.las" onChange={e=>setFile(e.target.files?.[0]??null)}/></Button>{upload.isError&&<Alert severity="error">{upload.error instanceof Error?upload.error.message:"Upload failed."}</Alert>}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" variant="contained" disabled={!name.trim()||!file||upload.isPending}>{upload.isPending?"Profiling…":"Upload"}</Button></DialogActions></form></Dialog>
  <Dialog open={Boolean(selected)} onClose={()=>setSelected(null)} fullWidth maxWidth="md"><DialogTitle>{selected?.name}</DialogTitle><DialogContent>{selected&&<Stack spacing={2}><Stack direction="row" gap={1}><Chip label={selected.source_type.toUpperCase()}/><Chip label={selected.status} color="success"/></Stack><Divider/><Stack direction={{xs:"column",sm:"row"}} gap={3}><Stack direction="row" gap={1} alignItems="center"><Table2 size={18}/>{selected.row_count?.toLocaleString()} rows</Stack><Stack direction="row" gap={1} alignItems="center"><Database size={18}/>{selected.column_count} columns</Stack><Stack direction="row" gap={1} alignItems="center"><HardDrive size={18}/>{bytes(selected.file_size_bytes)}</Stack></Stack><Box><Typography variant="subtitle2" mb={1}>Detected headers</Typography><Stack direction="row" gap={1} flexWrap="wrap">{selected.columns.map(c=><Chip key={c} label={c} size="small" variant="outlined"/>)}</Stack></Box></Stack>}</DialogContent><DialogActions><Button onClick={()=>setSelected(null)}>Close</Button></DialogActions></Dialog>
  <Dialog open={Boolean(deleteTarget)} onClose={()=>!remove.isPending&&setDeleteTarget(null)}><DialogTitle>Delete dataset?</DialogTitle><DialogContent><Typography>This permanently removes <strong>{deleteTarget?.name}</strong>, its stored file and linked experiments.</Typography>{remove.isError&&<Alert severity="error" sx={{mt:2}}>{remove.error instanceof Error?remove.error.message:"Deletion failed."}</Alert>}</DialogContent><DialogActions><Button onClick={()=>setDeleteTarget(null)}>Cancel</Button><Button color="error" variant="contained" onClick={()=>deleteTarget&&remove.mutate(deleteTarget.dataset_id)} disabled={remove.isPending}>{remove.isPending?"Deleting…":"Delete permanently"}</Button></DialogActions></Dialog>
 </Stack>;
}
