import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Alert, Box, Button, Chip, FormControl, Grid, InputLabel, MenuItem, Paper, Select, Slider, Stack, TextField, Typography } from "@mui/material";
import { BookmarkPlus, Pause, Play, RotateCcw } from "lucide-react";
import { fetchDatasets, fetchReplay } from "./platformApi";
const speeds=[{label:"0.5×",ms:700},{label:"1×",ms:350},{label:"2×",ms:175},{label:"5×",ms:70}];
export function DigitalReplayPanel(){
 const datasets=useQuery({queryKey:["platform","datasets"],queryFn:fetchDatasets}); const list=datasets.data??[];
 const [primary,setPrimary]=useState("");const id=primary||(list[0]?.dataset_id??"");const [secondary,setSecondary]=useState("");
 const a=useQuery({queryKey:["twin","a",id],queryFn:()=>fetchReplay(id),enabled:Boolean(id)});const b=useQuery({queryKey:["twin","b",secondary],queryFn:()=>fetchReplay(secondary),enabled:Boolean(secondary)});
 const events=a.data?.events??[];const min=events.length?Math.min(...events.map(x=>x.depth)):0;const max=events.length?Math.max(...events.map(x=>x.depth)):0;
 const [range,setRange]=useState<[number,number]>([0,0]);const [idx,setIdx]=useState(0);const [playing,setPlaying]=useState(false);const [speed,setSpeed]=useState(1);const [markers,setMarkers]=useState<Array<{depth:number;label:string}>>([]);const [label,setLabel]=useState("");
 useEffect(()=>{if(events.length){setRange([min,max]);setIdx(0);setPlaying(false);}},[id,min,max,events.length]);
 const filtered=useMemo(()=>events.filter(x=>x.depth>=Math.min(...range)&&x.depth<=Math.max(...range)),[events,range]);
 useEffect(()=>{if(!playing||filtered.length<2)return;const timer=window.setInterval(()=>setIdx(i=>{if(i>=filtered.length-1){setPlaying(false);return i;}return i+1;}),speeds[speed].ms);return()=>clearInterval(timer)},[playing,filtered.length,speed]);
 const e=filtered[Math.min(idx,Math.max(0,filtered.length-1))];const compare=b.data?.events?.length&&e?b.data.events.reduce((best,x)=>Math.abs(x.depth-e.depth)<Math.abs(best.depth-e.depth)?x:best,b.data.events[0]):undefined;
 const formationTops=useMemo(()=>{const tops:Array<{depth:number;lithology:string}>=[];let last="";for(const x of events){const lith=String(x.prediction.lithology??"");if(lith&&lith!==last){tops.push({depth:x.depth,lithology:lith});last=lith;}}return tops.slice(0,12)},[events]);
 return <Stack spacing={3}><Paper className="feature-hero" sx={{p:{xs:3,md:4}}}><Box sx={{position:"relative",zIndex:1}}><Typography variant="h4" fontWeight={900}>Digital Well Twin</Typography><Typography mt={1}>Replay, time-travel, annotate and compare interpreted wells through a synchronised depth domain.</Typography></Box></Paper>
 <Paper variant="outlined" sx={{p:2.5}}><Grid container spacing={2}><Grid item xs={12} md={4}><FormControl fullWidth><InputLabel>Primary well dataset</InputLabel><Select label="Primary well dataset" value={id} onChange={x=>setPrimary(x.target.value)}>{list.map(d=><MenuItem key={d.dataset_id} value={d.dataset_id}>{d.name}</MenuItem>)}</Select></FormControl></Grid><Grid item xs={12} md={4}><FormControl fullWidth><InputLabel>Comparison well</InputLabel><Select label="Comparison well" value={secondary} onChange={x=>setSecondary(x.target.value)}><MenuItem value="">None</MenuItem>{list.filter(d=>d.dataset_id!==id).map(d=><MenuItem key={d.dataset_id} value={d.dataset_id}>{d.name}</MenuItem>)}</Select></FormControl></Grid><Grid item xs={12} md={4}><FormControl fullWidth><InputLabel>Speed</InputLabel><Select label="Speed" value={speed} onChange={x=>setSpeed(Number(x.target.value))}>{speeds.map((s,i)=><MenuItem key={s.label} value={i}>{s.label}</MenuItem>)}</Select></FormControl></Grid></Grid></Paper>
 {events.length>0&&<><Paper variant="outlined" sx={{p:3}}><Typography variant="subtitle2">Interval selection</Typography><Slider value={range} min={min} max={max} onChange={(_,v)=>{setRange(v as [number,number]);setIdx(0);setPlaying(false)}} valueLabelDisplay="auto"/><Typography variant="body2">{range[0].toFixed(2)}–{range[1].toFixed(2)} m</Typography></Paper>
 {e&&<><Slider value={Math.min(idx,Math.max(0,filtered.length-1))} min={0} max={Math.max(0,filtered.length-1)} onChange={(_,v)=>{setIdx(v as number);setPlaying(false)}} valueLabelDisplay="auto" valueLabelFormat={v=>`${filtered[v]?.depth??v} m`}/><Stack direction="row" gap={1} flexWrap="wrap"><Button variant="contained" startIcon={playing?<Pause/>:<Play/>} onClick={()=>setPlaying(x=>!x)}>{playing?"Pause":"Play"}</Button><Button startIcon={<RotateCcw/>} onClick={()=>{setIdx(0);setPlaying(false)}}>Rewind</Button><TextField size="small" label="Marker label" value={label} onChange={x=>setLabel(x.target.value)}/><Button startIcon={<BookmarkPlus/>} onClick={()=>{setMarkers(m=>[...m,{depth:e.depth,label:label||`Marker ${m.length+1}`}]);setLabel("")}}>Place marker</Button></Stack>
 <Grid container spacing={2}><Grid item xs={12} lg={secondary?6:12}><TwinCard title={list.find(d=>d.dataset_id===id)?.name||"Primary well"} event={e}/></Grid>{secondary&&<Grid item xs={12} lg={6}>{compare?<TwinCard title={list.find(d=>d.dataset_id===secondary)?.name||"Comparison well"} event={compare}/>:<Alert severity="info">Comparison well has no replay samples.</Alert>}</Grid>}</Grid>
 <Grid container spacing={2}><Grid item xs={12} md={6}><Paper variant="outlined" sx={{p:3}}><Typography variant="h6">Formation tops</Typography>{formationTops.map(x=><Chip key={`${x.depth}-${x.lithology}`} sx={{m:.5}} label={`${x.lithology} top · ${x.depth.toFixed(2)} m`}/>)}</Paper></Grid><Grid item xs={12} md={6}><Paper variant="outlined" sx={{p:3}}><Typography variant="h6">Markers & AI annotations</Typography>{markers.length===0&&<Typography color="text.secondary">Place a marker at the current depth.</Typography>}{markers.map((m,i)=><Chip key={i} sx={{m:.5}} onDelete={()=>setMarkers(xs=>xs.filter((_,j)=>j!==i))} label={`${m.label} · ${m.depth.toFixed(2)} m`}/>)}{e.alerts.map(x=><Alert severity="warning" key={x} sx={{mt:1}}>{x} at {e.depth.toFixed(2)} m</Alert>)}</Paper></Grid></Grid></>}</>}
 {!id&&<Alert severity="info">Select a dataset to initialise the Digital Twin.</Alert>}</Stack>}
function TwinCard({title,event}:{title:string;event:{depth:number;logs:Record<string,number>;prediction:Record<string,string|number>;alerts:string[]}}){return <Paper className="digital-twin-card" sx={{p:3,height:"100%"}}><Typography variant="overline">{title}</Typography><Typography variant="h3" fontWeight={900}>{event.depth.toFixed(2)} m</Typography><Stack direction="row" gap={1} flexWrap="wrap" mt={1}>{Object.entries(event.prediction).map(([k,v])=><Chip key={k} label={`${k.replace(/_/g," ")}: ${typeof v==="number"?Number(v).toFixed(3):v}`}/>)}</Stack><Typography variant="subtitle2" mt={2}>Logs</Typography><Stack direction="row" gap={1} flexWrap="wrap">{Object.entries(event.logs).map(([k,v])=><Chip variant="outlined" key={k} label={`${k.toUpperCase()}: ${v}`}/>)}</Stack></Paper>}
