import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, LinearProgress, MenuItem, Paper, Select, Stack, TextField, Typography } from "@mui/material";
import { FlaskConical, Plus, Timer, Trophy } from "lucide-react";
import { createExperiment, fetchDatasets, fetchExperiments } from "./platformApi";

const tasks = ["hydrocarbon_classification","fluid_type_classification","lithology_classification","reservoir_quality_classification","pay_zone_classification","porosity_regression","permeability_regression","water_saturation_regression","anomaly_detection"];
const algorithms = ["XGBoost", "Random Forest", "LightGBM", "CatBoost", "ANN", "CNN", "Transformer"];
const pretty = (s: string) => s.replace(/_/g," ").replace(/\b\w/g, m => m.toUpperCase());

export function ExperimentManagerPanel() {
  const qc = useQueryClient(); const [open,setOpen]=useState(false); const [name,setName]=useState(""); const [task,setTask]=useState(tasks[0]); const [algorithm,setAlgorithm]=useState(algorithms[0]); const [datasetId,setDatasetId]=useState("");
  const query=useQuery({queryKey:["platform","experiments"],queryFn:fetchExperiments}); const datasets=useQuery({queryKey:["platform","datasets"],queryFn:fetchDatasets});
  const mutation=useMutation({mutationFn:()=>createExperiment({name,task,algorithm,dataset_id:datasetId||null,validation_strategy:"grouped_by_well"}),onSuccess:async()=>{await qc.invalidateQueries({queryKey:["platform"]});setOpen(false);setName("");}});
  const submit=(e:FormEvent)=>{e.preventDefault();if(name.trim())mutation.mutate();};
  return <Stack spacing={3}><Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" gap={2}><Box><Stack direction="row" gap={1} alignItems="center"><FlaskConical size={24}/><Typography variant="h5">Experiment manager</Typography></Stack><Typography variant="body2" color="text.secondary">Register reproducible model-development runs and validation strategies.</Typography></Box><Button variant="contained" startIcon={<Plus size={17}/>} onClick={()=>setOpen(true)}>New experiment</Button></Stack>{query.isLoading&&<LinearProgress/>}{query.isError&&<Alert severity="error">Unable to load experiments.</Alert>}<Stack spacing={1.5}>{(query.data??[]).map((e)=><Paper key={e.experiment_id} variant="outlined" sx={{p:2.25}}><Stack direction={{xs:"column",md:"row"}} justifyContent="space-between" gap={2}><Box><Stack direction="row" gap={1} alignItems="center"><Typography variant="h6">{e.name}</Typography><Chip size="small" label={e.status} color={e.status==="completed"?"success":e.status==="failed"?"error":"default"}/></Stack><Typography variant="body2" color="text.secondary">{pretty(e.task)} · {e.algorithm}</Typography></Box><Stack direction="row" gap={3}><Box><Typography variant="caption" color="text.secondary">Validation</Typography><Typography variant="body2">{e.validation_strategy||"Not set"}</Typography></Box><Box><Typography variant="caption" color="text.secondary">Metrics</Typography><Typography variant="body2">{Object.keys(e.metrics).length||"—"}</Typography></Box>{e.training_seconds!=null&&<Box><Typography variant="caption" color="text.secondary">Duration</Typography><Stack direction="row" gap={.5} alignItems="center"><Timer size={15}/><Typography variant="body2">{e.training_seconds}s</Typography></Stack></Box>}</Stack></Stack>{Object.keys(e.metrics).length>0&&<Stack direction="row" gap={1} mt={2} flexWrap="wrap">{Object.entries(e.metrics).map(([k,v])=><Chip key={k} icon={<Trophy size={14}/>} label={`${pretty(k)}: ${String(v)}`} size="small" variant="outlined"/>)}</Stack>}</Paper>)}</Stack>{!query.isLoading&&(query.data??[]).length===0&&<Paper variant="outlined" sx={{p:5,textAlign:"center"}}><FlaskConical size={42}/><Typography variant="h6" mt={1}>No experiments registered</Typography></Paper>}
  <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><form onSubmit={submit}><DialogTitle>Create experiment</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField label="Experiment name" required value={name} onChange={e=>setName(e.target.value)}/><FormControl><InputLabel>Task</InputLabel><Select label="Task" value={task} onChange={e=>setTask(e.target.value)}>{tasks.map(t=><MenuItem key={t} value={t}>{pretty(t)}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>Algorithm</InputLabel><Select label="Algorithm" value={algorithm} onChange={e=>setAlgorithm(e.target.value)}>{algorithms.map(a=><MenuItem key={a} value={a}>{a}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>Dataset</InputLabel><Select label="Dataset" value={datasetId} onChange={e=>setDatasetId(e.target.value)}><MenuItem value="">No dataset selected</MenuItem>{(datasets.data??[]).map(d=><MenuItem key={d.dataset_id} value={d.dataset_id}>{d.name}</MenuItem>)}</Select></FormControl>{mutation.isError&&<Alert severity="error">{mutation.error instanceof Error?mutation.error.message:"Creation failed."}</Alert>}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" variant="contained" disabled={!name.trim()||mutation.isPending}>{mutation.isPending?"Creating…":"Create"}</Button></DialogActions></form></Dialog></Stack>;
}
