import { useQuery } from "@tanstack/react-query";
import { Alert, Box, Button, Chip, Grid, LinearProgress, Paper, Stack, Typography } from "@mui/material";
import { BrainCircuit, MapPinned, ShieldCheck } from "lucide-react";
import { fetchCalibration, fetchContinualLearning } from "./platformApi";

export function Sprint2GovernancePanel(){
 const calibration=useQuery({queryKey:["sprint2","calibration"],queryFn:fetchCalibration,retry:2});
 const learning=useQuery({queryKey:["sprint2","learning"],queryFn:fetchContinualLearning,retry:2});
 if(calibration.isLoading||learning.isLoading)return <LinearProgress/>;
 if(calibration.isError||learning.isError)return <Alert severity="warning" action={<Button size="small" onClick={()=>{void calibration.refetch();void learning.refetch();}}>Retry</Button>}>Nigerian calibration data is temporarily unavailable. The module remains installed and accessible.</Alert>;
 const c=calibration.data;const l=learning.data;
 if(!c||!l)return <Alert severity="info">Calibration records have not yet been initialised.</Alert>;
 return <Stack spacing={3}>
  <Paper className="feature-hero" sx={{p:{xs:3,md:4}}}><Stack direction="row" gap={1} alignItems="center" sx={{position:"relative",zIndex:1}}><MapPinned/><Box><Typography variant="overline">Sovereign model intelligence</Typography><Typography variant="h4" fontWeight={900}>Nigerian Calibration & Continual Learning</Typography><Typography mt={.5}>Governed regional calibration for Nigerian subsurface datasets and model updates.</Typography></Box></Stack></Paper>
  <Grid container spacing={3}>
   <Grid item xs={12} lg={6}><Paper variant="outlined" sx={{p:3,height:"100%"}}><Typography variant="overline">Regional knowledge base</Typography><Typography variant="h5" fontWeight={800}>{c.region||"Niger Delta"}</Typography><Chip sx={{mt:1}} color={c.status==="active"?"success":"default"} label={c.status||"baseline"}/><Grid container spacing={2} mt={1}>{[["Datasets",c.datasets??0],["Validated",c.validated_datasets??0],["Samples",c.training_samples??0]].map(([a,b])=><Grid item xs={4} key={String(a)}><Box sx={{p:2,bgcolor:"action.hover",borderRadius:2}}><Typography variant="caption" color="text.secondary">{a}</Typography><Typography variant="h6" fontWeight={800}>{Number(b??0).toLocaleString()}</Typography></Box></Grid>)}</Grid><Typography fontWeight={700} mt={2}>Supported formations</Typography><Stack direction="row" gap={1} flexWrap="wrap" mt={1}>{(c.formations??[]).map(x=><Chip key={x} label={x}/>)}</Stack><Typography fontWeight={700} mt={2}>Supported curves</Typography><Typography color="text.secondary">{(c.supported_curves??[]).join(" · ")||"No curves registered"}</Typography><Alert severity="info" sx={{mt:2}}>{c.governance||"Expert validation required before deployment."}</Alert></Paper></Grid>
   <Grid item xs={12} lg={6}><Paper variant="outlined" sx={{p:3,height:"100%"}}><Stack direction="row" gap={1}><BrainCircuit/><Typography variant="h6">Continual-learning gate</Typography></Stack><Grid container spacing={2} mt={.5}><Grid item xs={6}><Box sx={{p:2,bgcolor:"action.hover",borderRadius:2}}><Typography variant="caption">Eligible datasets</Typography><Typography variant="h5" fontWeight={800}>{l.knowledge_base?.eligible_datasets??0}</Typography></Box></Grid><Grid item xs={6}><Box sx={{p:2,bgcolor:"action.hover",borderRadius:2}}><Typography variant="caption">Admitted datasets</Typography><Typography variant="h5" fontWeight={800}>{l.knowledge_base?.admitted_datasets??0}</Typography></Box></Grid></Grid><Typography fontWeight={700} mt={2}>Validation controls</Typography><Stack spacing={1} mt={1}>{(l.controls??[]).map(x=><Stack direction="row" gap={1} key={x}><ShieldCheck size={18}/><Typography>{x}</Typography></Stack>)}</Stack><Typography fontWeight={700} mt={2}>Retraining queue</Typography>{(l.retraining_queue??[]).length?(l.retraining_queue??[]).map(x=><Box key={x.dataset_id} sx={{mt:1,p:1.5,borderRadius:2,bgcolor:"action.hover"}}><Typography fontWeight={700}>{x.name}</Typography><Typography variant="caption" color="text.secondary">{x.status.replace(/_/g," ")}</Typography></Box>):<Typography color="text.secondary">No datasets waiting.</Typography>}</Paper></Grid>
  </Grid>
 </Stack>;
}
