import { useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Alert, Box, Button, Card, CardContent, Checkbox, Chip, FormControl, FormControlLabel, Grid, InputLabel, LinearProgress, MenuItem, Select, Stack, TextField, Typography } from "@mui/material";
import { Bot, Database, Play } from "lucide-react";
import { apiRequest } from "../../api/http";
import { fetchDatasetPreview, fetchDatasets } from "../platform/platformApi";

type Agent={key:string;name:string;domain:string};
type Finding={title:string;statement:string;confidence:number;severity:string;evidence:string[];recommendations:string[];metrics:Record<string,unknown>};
type AgentResult={agent_key:string;agent_name:string;domain:string;confidence:number;findings:Finding[];summary:string;limitations:string[]};
type PanelResult={panel_id:string;agents:AgentResult[];consensus:{overall_confidence:number;summary:string;recommendations:string[];agreements:string[];disagreements:Array<{topic:string;explanation:string;severity:string}>;missing_evidence:string[]}};

export function AgentsWorkspace(){
 const agentsQ=useQuery({queryKey:["agents"],queryFn:()=>apiRequest<{count:number;agents:Agent[]}>("/agents")});
 const datasetsQ=useQuery({queryKey:["platform","datasets"],queryFn:fetchDatasets});
 const [selected,setSelected]=useState<string[]>([]); const [datasetChoice,setDatasetChoice]=useState(""); const [wellId,setWellId]=useState(""); const [rowLimit,setRowLimit]=useState(250); const [result,setResult]=useState<PanelResult|null>(null);
 const datasetId=datasetChoice||datasetsQ.data?.[0]?.dataset_id||""; const selectedDataset=(datasetsQ.data??[]).find(d=>d.dataset_id===datasetId);
 const previewQ=useQuery({queryKey:["platform","preview",datasetId],queryFn:()=>fetchDatasetPreview(datasetId),enabled:Boolean(datasetId)});
 const inferredWell=useMemo(()=>wellId.trim()||selectedDataset?.name||datasetId,[wellId,selectedDataset,datasetId]);
 const rows=useMemo(()=>previewQ.data?.rows.slice(0,rowLimit)??[],[previewQ.data,rowLimit]);
 const mutation=useMutation({mutationFn:async()=>{if(!datasetId)throw new Error("Select an uploaded dataset first.");if(!rows.length)throw new Error("The selected dataset contains no preview rows.");const payload={inputs:{dataset_id:datasetId,dataset_name:selectedDataset?.name,well_id:inferredWell,rows,columns:previewQ.data?.columns??[]},context:{source:"uploaded_dataset",dataset_id:datasetId,row_count:rows.length},agent_keys:selected.length?selected:undefined};return apiRequest<PanelResult>(selected.length===1?`/agents/${selected[0]}/run`:"/agents/panel/run",{method:"POST",body:JSON.stringify(payload)});},onSuccess:setResult});
 const all=agentsQ.data?.agents??[];
 return <Stack spacing={2.5}>
  <Card className="feature-hero" variant="outlined"><CardContent><Stack direction={{xs:"column",md:"row"}} justifyContent="space-between" gap={2}><Box><Typography variant="h4">Multi-Agent Dataset Interpretation</Typography><Typography sx={{mt:1}}>Agents now consume records directly from datasets uploaded to PetroEdge. No static JSON is required.</Typography></Box><Chip icon={<Database size={16}/>} label={selectedDataset?.name??"No dataset selected"} sx={{alignSelf:"center",bgcolor:"rgba(255,255,255,.16)",color:"white"}}/></Stack></CardContent></Card>
  {(agentsQ.isLoading||datasetsQ.isLoading)&&<LinearProgress/>}{agentsQ.isError&&<Alert severity="error">{agentsQ.error instanceof Error?agentsQ.error.message:"Unable to load agents."}</Alert>}{datasetsQ.isError&&<Alert severity="error">{datasetsQ.error instanceof Error?datasetsQ.error.message:"Unable to load datasets."}</Alert>}
  <Grid container spacing={2}>
   <Grid item xs={12} lg={5}><Card variant="outlined"><CardContent><Stack spacing={2}><Stack direction="row" gap={1} alignItems="center"><Bot/><Typography variant="h6">Evidence package</Typography></Stack><FormControl fullWidth><InputLabel>Uploaded dataset</InputLabel><Select label="Uploaded dataset" value={datasetId} onChange={e=>{setDatasetChoice(e.target.value);setResult(null)}}>{(datasetsQ.data??[]).map(d=><MenuItem key={d.dataset_id} value={d.dataset_id}>{d.name} · {d.source_type.toUpperCase()}</MenuItem>)}</Select></FormControl><TextField label="Well or asset identifier" value={wellId} onChange={e=>setWellId(e.target.value)} placeholder={selectedDataset?.name??"Optional"} helperText="Leave blank to use the dataset name."/><TextField label="Maximum rows supplied to agents" type="number" value={rowLimit} onChange={e=>setRowLimit(Math.max(10,Math.min(800,Number(e.target.value)||250)))} inputProps={{min:10,max:800}}/>{previewQ.isLoading&&<LinearProgress/>}{previewQ.data&&<Box sx={{p:1.5,bgcolor:"grey.50",borderRadius:2}}><Typography variant="body2"><b>Available rows:</b> {previewQ.data.total_rows}</Typography><Typography variant="body2"><b>Rows used:</b> {rows.length}</Typography><Typography variant="body2"><b>Detected columns:</b> {previewQ.data.columns.join(", ")}</Typography></Box>}<Box><Typography variant="subtitle2" gutterBottom>Specialists</Typography><Grid container>{all.map(a=><Grid item xs={12} sm={6} key={a.key}><FormControlLabel control={<Checkbox checked={selected.includes(a.key)} onChange={e=>setSelected(v=>e.target.checked?[...v,a.key]:v.filter(x=>x!==a.key))}/>} label={<Box><Typography variant="body2" fontWeight={700}>{a.name}</Typography><Typography variant="caption" color="text.secondary">{a.domain.replace(/_/g," ")}</Typography></Box>}/></Grid>)}</Grid><Typography variant="caption" color="text.secondary">Leave all unchecked to run the full panel.</Typography></Box><Button variant="contained" size="large" startIcon={<Play size={18}/>} disabled={mutation.isPending||!datasetId||!rows.length} onClick={()=>mutation.mutate()}>{mutation.isPending?"Analysing uploaded data…":"Run agents on dataset"}</Button>{mutation.isError&&<Alert severity="error">{mutation.error instanceof Error?mutation.error.message:"Agent execution failed."}</Alert>}</Stack></CardContent></Card></Grid>
   <Grid item xs={12} lg={7}>{!result?<Alert severity="info">Choose an uploaded dataset and run one specialist or the complete agent panel.</Alert>:<Stack spacing={2}><Card variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between" gap={2}><Box><Typography variant="overline">Panel consensus</Typography><Typography variant="h5">{result.consensus.summary}</Typography></Box><Chip color="success" label={`${Math.round(result.consensus.overall_confidence*100)}% confidence`}/></Stack><LinearProgress variant="determinate" value={result.consensus.overall_confidence*100} sx={{my:2,height:8,borderRadius:4}}/>{result.consensus.recommendations.map(x=><Typography key={x} variant="body2">• {x}</Typography>)}</CardContent></Card>{result.agents.map(agent=><Card variant="outlined" key={agent.agent_key}><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography variant="h6">{agent.agent_name}</Typography><Typography color="text.secondary">{agent.domain.replace(/_/g," ")}</Typography></Box><Chip label={`${Math.round(agent.confidence*100)}%`} color={agent.confidence>=.7?"success":"warning"}/></Stack><Typography sx={{my:1.5}}>{agent.summary}</Typography>{agent.findings.map(f=><Box key={f.title} sx={{mt:2,p:2,bgcolor:"grey.50",borderRadius:2}}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>{f.title}</Typography><Chip size="small" label={f.severity}/></Stack><Typography mt={1}>{f.statement}</Typography>{f.evidence.map(x=><Typography key={x} variant="body2" color="text.secondary">Evidence: {x}</Typography>)}{f.recommendations.map(x=><Typography key={x} variant="body2" mt={.5}>Recommendation: {x}</Typography>)}</Box>)}</CardContent></Card>)}</Stack>}</Grid>
  </Grid>
 </Stack>
}
