import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Grid, LinearProgress, Stack, Typography } from "@mui/material";
import { Boxes, CheckCircle2, Cpu, ExternalLink, Info } from "lucide-react";
import { apiRequest } from "../../api/http";
type Module={key:string;name:string;description:string;resource_class:"light"|"medium"|"heavy";capabilities:string[];enabled:boolean;lazy:boolean};type Catalogue={architecture:string;module_count:number;modules:Module[]};
const destinations:[RegExp,string][]=[[/agent/i,"Agents"],[/workflow/i,"Workflows"],[/twin/i,"Digital Twins"],[/rule/i,"Rules"],[/event/i,"Events"],[/report/i,"Reports"],[/edge|temporal|gru/i,"Edge"],[/monitor|health/i,"System Health"],[/dataset|ingest|platform/i,"Datasets"],[/model|registry|governance/i,"Models"],[/job/i,"Jobs"],[/stream|realtime/i,"Live events"],[/reservoir|petrophys|well.?log/i,"Reservoir Intelligence"]];
function destination(m:Module){const text=[m.key,m.name,m.description,...m.capabilities].join(" ");return destinations.find(([r])=>r.test(text))?.[1]??null;}
export function PluginsWorkspace(){const q=useQuery({queryKey:["builtin-modules"],queryFn:()=>apiRequest<Catalogue>("/plugins/modules")});const [active,setActive]=useState<Module|null>(null);const functional=useMemo(()=>(q.data?.modules??[]).filter(m=>m.enabled&&destination(m)),[q.data]);const open=(label:string)=>window.dispatchEvent(new CustomEvent("petroedge:navigate",{detail:label}));return <Stack spacing={2.5}><Card className="feature-hero" variant="outlined"><CardContent><Typography variant="h4">Built-in Capability Catalogue</Typography><Typography sx={{mt:1}}>Enabled backend modules are linked directly to the corresponding operational workspace.</Typography></CardContent></Card>{q.isLoading&&<LinearProgress/>}{q.isError&&<Alert severity="error">Unable to load modules.</Alert>}{q.data&&<><Stack direction="row" gap={1}><Chip label={`${q.data.module_count} registered`}/><Chip color="success" label={`${functional.length} connected to frontend`}/></Stack><Grid container spacing={2}>{q.data.modules.map(m=>{const target=destination(m);return <Grid item xs={12} sm={6} lg={4} key={m.key}><Card variant="outlined" sx={{height:"100%",bgcolor:"background.paper",opacity:1}}><CardContent sx={{height:"100%",display:"flex",flexDirection:"column"}}><Stack direction="row" justifyContent="space-between"><Box className="metric-icon"><Cpu size={20}/></Box><Chip size="small" color={m.enabled?"success":"default"} icon={<CheckCircle2 size={14}/>} label={m.enabled?"Enabled":"Disabled"}/></Stack><Typography variant="h6" mt={2}>{m.name}</Typography><Typography color="text.secondary" mt={.75} flex={1}>{m.description}</Typography><Stack direction="row" gap={0.75} mt={2} flexWrap="wrap">{m.capabilities.slice(0,3).map(c=><Chip key={c} size="small" label={c}/>)}</Stack><Stack direction="row" gap={1} mt={2}>{target&&m.enabled?<Button variant="contained" startIcon={<ExternalLink size={16}/>} onClick={()=>open(target)}>Open {target}</Button>:<Button disabled>Backend catalogue only</Button>}<Button startIcon={<Info size={16}/>} onClick={()=>setActive(m)}>Details</Button></Stack></CardContent></Card></Grid>})}</Grid></>}<Dialog open={Boolean(active)} onClose={()=>setActive(null)} fullWidth maxWidth="sm"><DialogTitle>{active?.name}</DialogTitle><DialogContent><Typography color="text.secondary">{active?.description}</Typography><Stack spacing={1} mt={2}>{active?.capabilities.map(c=><Box key={c} sx={{p:1.25,bgcolor:"grey.50",borderRadius:1.5}}><Typography fontWeight={700}>{c}</Typography></Box>)}</Stack></DialogContent><DialogActions><Button onClick={()=>setActive(null)}>Close</Button>{active&&destination(active)&&<Button variant="contained" onClick={()=>{open(destination(active)!);setActive(null)}}>Open workspace</Button>}</DialogActions></Dialog></Stack>}
