from app.ai.metadata import ModelCapability,ModelFamily,ModelTask
BUILTIN_CAPABILITIES=(
ModelCapability(key='random_forest',display_name='Random Forest',family=ModelFamily.classical_ml,tasks=[ModelTask.classification,ModelTask.regression],framework='scikit-learn',edge_ready=True,onnx_export=True,description='Robust tree ensemble for lithology and petrophysical prediction.'),
ModelCapability(key='gradient_boosting',display_name='Gradient Boosting',family=ModelFamily.gradient_boosting,tasks=[ModelTask.classification,ModelTask.regression],framework='scikit-learn',edge_ready=True,onnx_export=True,description='Sequential boosted trees for structured subsurface data.'),
ModelCapability(key='xgboost',display_name='XGBoost',family=ModelFamily.gradient_boosting,tasks=[ModelTask.classification,ModelTask.regression,ModelTask.forecasting],framework='xgboost',supports_gpu=True,edge_ready=True,onnx_export=True,description='Boosted trees for hydrocarbon detection and forecasting.'),
ModelCapability(key='lightgbm',display_name='LightGBM',family=ModelFamily.gradient_boosting,tasks=[ModelTask.classification,ModelTask.regression],framework='lightgbm',supports_gpu=True,edge_ready=True,onnx_export=True,description='Efficient boosting for large well-log datasets.'),
ModelCapability(key='catboost',display_name='CatBoost',family=ModelFamily.gradient_boosting,tasks=[ModelTask.classification,ModelTask.regression],framework='catboost',supports_gpu=True,onnx_export=True,description='Boosting with categorical-feature support.'),
ModelCapability(key='ann',display_name='Artificial Neural Network',family=ModelFamily.deep_learning,tasks=[ModelTask.classification,ModelTask.regression],framework='PyTorch/TensorFlow',supports_gpu=True,edge_ready=True,onnx_export=True,description='Dense neural network for nonlinear petrophysical relationships.'),
ModelCapability(key='cnn',display_name='Convolutional Neural Network',family=ModelFamily.deep_learning,tasks=[ModelTask.classification,ModelTask.reconstruction],framework='PyTorch/TensorFlow',supports_gpu=True,edge_ready=True,onnx_export=True,description='Convolutional architecture for log windows and seismic imagery.'),
ModelCapability(key='lstm',display_name='LSTM',family=ModelFamily.sequence,tasks=[ModelTask.forecasting,ModelTask.reconstruction],framework='PyTorch/TensorFlow',supports_gpu=True,supports_streaming=True,causal=True,edge_ready=True,onnx_export=True,description='Sequence model for temporal forecasting.'),
ModelCapability(key='gru',display_name='GRU',family=ModelFamily.sequence,tasks=[ModelTask.forecasting,ModelTask.classification,ModelTask.anomaly_detection],framework='PyTorch/TensorFlow/ONNX Runtime',supports_gpu=True,supports_streaming=True,causal=True,edge_ready=True,onnx_export=True,description='Causal low-latency sequence model for live and edge inference.'),
ModelCapability(key='bigru',display_name='Bidirectional GRU',family=ModelFamily.sequence,tasks=[ModelTask.classification,ModelTask.reconstruction,ModelTask.forecasting],framework='PyTorch/TensorFlow/ONNX Runtime',supports_gpu=True,supports_streaming=False,causal=False,edge_ready=False,onnx_export=True,description='Bidirectional model for historical replay and contextual interpretation.'),
ModelCapability(key='voting_ensemble',display_name='Voting Ensemble',family=ModelFamily.ensemble,tasks=[ModelTask.classification,ModelTask.regression],framework='PetroEdge ensemble',description='Combines compatible estimators.'),
ModelCapability(key='stacked_ensemble',display_name='Stacked Ensemble',family=ModelFamily.ensemble,tasks=[ModelTask.classification,ModelTask.regression,ModelTask.forecasting],framework='PetroEdge ensemble',description='Out-of-fold stacking with a meta-learner.'),)