import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Alert, Box, Button, Chip, FormControl, InputLabel, MenuItem, Paper, Select, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import { BarChart3, DatabaseZap, RefreshCw } from "lucide-react";
import { SafePlot } from "../../components/SafePlot";
import { fetchDatasetPreview, fetchDatasets, fetchInterpretation } from "../platform/platformApi";

type Row=Record<string,unknown>;
const aliases:Record<string,string[]>={depth:["depth","depth_m","dept","md","tvd","tvdss"],gr:["gr","gamma_ray","gamma_ray_api","gr_comp.gapi"],rt:["rt","ild","resistivity","resistivity_ohmm","rt_comp.ohmm"],rhob:["rhob","density","density_gcc","rhob_comp.g/c3"],nphi:["nphi","neutron","neutron_porosity","neutron_porosity_vv","nphi_comp.v/v"],dt:["dt","sonic","sonic_usft","ac"],phi:["phi","porosity","effective_porosity"],pef:["pef","photoelectric_factor"]};
const norm=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]/g,"");
function findColumn(columns:string[],key:string){const map=new Map(columns.map(c=>[norm(c),c]));for(const a of aliases[key]??[]) {const c=map.get(norm(a));if(c)return c;}return undefined;}
const num=(v:unknown)=>{const x=typeof v==="number"?v:Number(v);return Number.isFinite(x)?x:null};
function inferLithology(row:Row,c:Record<string,string|undefined>){const gr=num(c.gr?row[c.gr]:null);const rhob=num(c.rhob?row[c.rhob]:null);const nphi=num(c.nphi?row[c.nphi]:null);if(gr!==null&&gr>=90)return "Shale";if(gr!==null&&gr<60&&rhob!==null&&rhob<2.55)return "Sandstone";if(rhob!==null&&rhob>2.68)return "Carbonate/compact";if(nphi!==null&&rhob!==null&&nphi<0.12&&rhob<2.45)return "Gas-bearing clean formation";return "Mixed/uncertain";}
function inferFluid(row:Row,c:Record<string,string|undefined>){const rt=num(c.rt?row[c.rt]:null);const phi=num(c.phi?row[c.phi]:null)??num(c.nphi?row[c.nphi]:null);const rhob=num(c.rhob?row[c.rhob]:null);const nphi=num(c.nphi?row[c.nphi]:null);if(rt!==null&&rt>20&&phi!==null&&phi>0.08){if(rhob!==null&&nphi!==null&&rhob<2.45&&nphi<0.15)return "Gas indication";return "Hydrocarbon indication";}if(rt!==null&&rt<5)return "Water-bearing indication";return "Uncertain";}
const axisTitle=(x:string,y:string)=>({xaxis:{title:x,automargin:true},yaxis:{title:y,automargin:true},height:390,margin:{l:70,r:20,t:50,b:65},paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)"});
export function WellLogViewer(){
 const datasets=useQuery({queryKey:["platform","datasets"],queryFn:fetchDatasets}); const [chosen,setChosen]=useState(""); const datasetId=chosen||datasets.data?.[0]?.dataset_id||"";
 const preview=useQuery({queryKey:["welllogs","preview",datasetId],queryFn:()=>fetchDatasetPreview(datasetId),enabled:Boolean(datasetId)}); const interpretation=useQuery({queryKey:["welllogs","interpretation",datasetId],queryFn:()=>fetchInterpretation(datasetId),enabled:Boolean(datasetId),retry:false});
 const columns=preview.data?.columns??[]; const c=useMemo(()=>Object.fromEntries(Object.keys(aliases).map(k=>[k,findColumn(columns,k)])) as Record<string,string|undefined>,[columns]);
 const depthValues=(preview.data?.rows??[]).map(r=>c.depth?num(r[c.depth]):null).filter((x):x is number=>x!==null); const minDepth=depthValues.length?Math.min(...depthValues):0; const maxDepth=depthValues.length?Math.max(...depthValues):0;
 const [top,setTop]=useState<string>(""); const [base,setBase]=useState<string>(""); const [entire,setEntire]=useState(true); const rows=preview.data?.rows??[];
 const selected=useMemo(()=>rows.filter(r=>{if(entire||!c.depth)return true;const d=num(r[c.depth]);if(d===null)return false;const t=top===""?minDepth:Number(top);const b=base===""?maxDepth:Number(base);return d>=Math.min(t,b)&&d<=Math.max(t,b);}),[rows,entire,c.depth,top,base,minDepth,maxDepth]);
 const shown=selected.slice(0,100); const available=Object.entries(c).filter(([,v])=>v).map(([k])=>k.toUpperCase());
 const plot=(xKey:string,yKey:string,title:string,logX=false)=>{const xc=c[xKey],yc=c[yKey];if(!xc||!yc)return null;const pts=selected.map(r=>({x:num(r[xc]),y:num(r[yc])})).filter(p=>p.x!==null&&p.y!==null);if(!pts.length)return null;return <Paper variant="outlined" sx={{p:1.5}}><Typography fontWeight={800} px={1}>{title}</Typography><SafePlot data={[{type:"scattergl",mode:"markers",x:pts.map(p=>p.x),y:pts.map(p=>p.y),marker:{size:6,opacity:.65},hovertemplate:`${xc}: %{x}<br>${yc}: %{y}<extra></extra>`}]} layout={{...axisTitle(xc,yc),xaxis:{...axisTitle(xc,yc).xaxis,type:logX?"log":"linear"}}} config={{responsive:true,displaylogo:false,scrollZoom:true,toImageButtonOptions:{format:"png",filename:title.replace(/\s+/g,"-").toLowerCase(),scale:2}}}/></Paper>};
 return <Stack spacing={3}>
  <Paper className="hero-panel" sx={{p:3}}><Stack direction={{xs:"column",md:"row"}} justifyContent="space-between" gap={2}><Box><Stack direction="row" gap={1} alignItems="center"><BarChart3/><Typography variant="h4" fontWeight={900}>Well Log Analysis</Typography></Stack><Typography mt={1}>Select a registered dataset, inspect its first 100 samples, define a depth interval and visualise industry-relevant relationships.</Typography></Box><Button startIcon={<RefreshCw/>} variant="contained" onClick={()=>{void datasets.refetch();void preview.refetch();}}>Refresh</Button></Stack></Paper>
  {datasets.isError&&<Alert severity="error">Datasets could not be loaded.</Alert>}{!datasetId&&<Alert severity="info">Upload a well-log dataset in the Datasets tab first.</Alert>}
  <Paper variant="outlined" sx={{p:3}}><Stack spacing={2}><FormControl fullWidth><InputLabel>Dataset</InputLabel><Select value={datasetId} label="Dataset" onChange={e=>setChosen(e.target.value)}>{(datasets.data??[]).map(d=><MenuItem key={d.dataset_id} value={d.dataset_id}>{d.name}</MenuItem>)}</Select></FormControl><Stack direction={{xs:"column",md:"row"}} gap={2}><Button variant={entire?"contained":"outlined"} onClick={()=>setEntire(true)}>Entire dataset</Button><TextField label="Top depth" type="number" value={top} disabled={entire} onChange={e=>setTop(e.target.value)} helperText={c.depth?`Minimum ${minDepth.toFixed(1)}`:"Depth column unavailable"}/><TextField label="Base depth" type="number" value={base} disabled={entire} onChange={e=>setBase(e.target.value)} helperText={c.depth?`Maximum ${maxDepth.toFixed(1)}`:"Depth column unavailable"}/><Button variant={!entire?"contained":"outlined"} disabled={!c.depth} onClick={()=>setEntire(false)}>Use interval</Button></Stack><Stack direction="row" gap={1} flexWrap="wrap"><Chip icon={<DatabaseZap size={15}/>} label={`${selected.length} selected rows`}/>{available.map(x=><Chip key={x} label={x}/>)}</Stack></Stack></Paper>
  {interpretation.data&&<Paper variant="outlined" sx={{p:2.5}}><Typography variant="h6">Interval interpretation</Typography><Stack direction="row" gap={1} flexWrap="wrap" mt={1}>{Object.entries(interpretation.data.summary??{}).slice(0,8).map(([k,v])=><Chip key={k} label={`${k.replace(/_/g," ")}: ${String(v)}`}/>)}</Stack></Paper>}
  {preview.data&&<Paper variant="outlined" sx={{overflow:"auto"}}><Box sx={{p:2}}><Typography variant="h6">Data preview</Typography><Typography color="text.secondary">First 100 samples from the current selection. Lithology and fluid columns are screening interpretations.</Typography></Box><Table size="small"><TableHead><TableRow>{columns.slice(0,10).map(x=><TableCell key={x}>{x}</TableCell>)}<TableCell>Lithology</TableCell><TableCell>Fluid type</TableCell></TableRow></TableHead><TableBody>{shown.map((r,i)=><TableRow key={i} hover>{columns.slice(0,10).map(x=><TableCell key={x}>{String(r[x]??"")}</TableCell>)}<TableCell>{inferLithology(r,c)}</TableCell><TableCell>{inferFluid(r,c)}</TableCell></TableRow>)}</TableBody></Table></Paper>}
  <Box display="grid" gridTemplateColumns={{xs:"1fr",xl:"repeat(2,1fr)"}} gap={2}>{plot("nphi","rhob","NPHI vs RHOB")}{plot("phi","rt","PHI vs RT · Pickett screening",false)}{plot("gr","rhob","GR vs RHOB")}{plot("gr","nphi","GR vs NPHI")}{plot("rhob","dt","RHOB vs DT")}{plot("gr","rt","GR vs RT",false)}{plot("pef","rhob","PEF vs RHOB")}</Box>
  {selected.length>0&&!c.nphi&&!c.rhob&&!c.gr&&!c.rt&&<Alert severity="warning">Recognised petroleum log mnemonics were not found. Rename or map the dataset columns before crossplot analysis.</Alert>}
 </Stack>;
}
