import { FormEvent, useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, LinearProgress, MenuItem, Paper, Stack, TextField, Typography } from "@mui/material";
import { Database, Download, FileUp, GitBranch, HardDrive, RefreshCw, Search, Table2, Trash2, WandSparkles, Workflow } from "lucide-react";
import { deleteDataset, downloadReport, fetchDatasetLineage, fetchDatasets, generateDatasetReport, processLasDataset, uploadDataset, type DatasetSummary } from "./platformApi";
const bytes=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
const TYPES=["well_log","fluid_data","pvt_data","formation_water","fluid_contacts","pressure_data","temperature_data","core_data","production_data"];
export function DatasetRegistryPanel(){
 const qc=useQueryClient();const [open,setOpen]=useState(false);const [name,setName]=useState("");const [description,setDescription]=useState("");const [file,setFile]=useState<File|null>(null);const [datasetType,setDatasetType]=useState("well_log");const [fieldName,setFieldName]=useState("");const [wellName,setWellName]=useState("");const [reservoirName,setReservoirName]=useState("");const [search,setSearch]=useState("");const [selected,setSelected]=useState<DatasetSummary|null>(null);const [deleteTarget,setDeleteTarget]=useState<DatasetSummary|null>(null);const [notice,setNotice]=useState("");
 const query=useQuery({queryKey:["platform","datasets"],queryFn:fetchDatasets});const lineage=useQuery({queryKey:["platform","lineage",selected?.dataset_id],queryFn:()=>fetchDatasetLineage(selected!.dataset_id),enabled:Boolean(selected)});
 const refresh=async()=>Promise.all([qc.invalidateQueries({queryKey:["platform"]}),qc.invalidateQueries({queryKey:["platform","datasets"]})]);
 const upload=useMutation({mutationFn:()=>uploadDataset(name,description,file!,datasetType,fieldName,wellName,reservoirName),onSuccess:async()=>{await refresh();setOpen(false);setName("");setDescription("");setFile(null);setNotice("Dataset registered with immutable version metadata.");}});
 const processLas=useMutation({mutationFn:(id:string)=>processLasDataset(id,{}),onSuccess:async(d)=>{await refresh();setSelected(d);setNotice(`Created ${d.version_id} without modifying the raw LAS file.`);}});
 const report=useMutation({mutationFn:async(id:string)=>{const result=await generateDatasetReport(id);await downloadReport(result.report_id,"pdf");},onSuccess:()=>setNotice("PDF report downloaded.")});
 const remove=useMutation({mutationFn:(id:string)=>deleteDataset(id),onSuccess:async()=>{await refresh();setDeleteTarget(null);setSelected(null);}});
 const rows=useMemo(()=>(query.data??[]).filter(d=>`${d.name} ${d.file_name} ${d.dataset_type} ${d.field_name??""} ${d.well_name??""}`.toLowerCase().includes(search.toLowerCase())),[query.data,search]);
 useEffect(()=>{const pendingId=sessionStorage.getItem("petroedge_open_dataset_id");if(!pendingId||!query.data)return;const dataset=query.data.find(item=>item.dataset_id===pendingId);if(dataset){setSelected(dataset);sessionStorage.removeItem("petroedge_open_dataset_id");}},[query.data]);
 const submit=(e:FormEvent)=>{e.preventDefault();if(name.trim()&&file)upload.mutate();};
 return <Stack spacing={3}>{notice&&<Alert severity="success" onClose={()=>setNotice("")}>{notice}</Alert>}
 <Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" gap={2}><Box><Stack direction="row" gap={1} alignItems="center"><Database size={24}/><Typography variant="h5">Unified dataset registry</Typography></Stack><Typography variant="body2" color="text.secondary">Typed records, immutable LAS versions, lineage, fluid evidence and operational PDF exports.</Typography></Box><Stack direction="row" gap={1}><Button variant="outlined" startIcon={<RefreshCw size={16}/>} onClick={()=>void refresh()}>Refresh</Button><Button variant="outlined" startIcon={<Workflow size={16}/>} onClick={()=>window.dispatchEvent(new CustomEvent("petroedge:navigate",{detail:{tab:"Operations"}}))}>Operations</Button><Button variant="contained" startIcon={<FileUp size={17}/>} onClick={()=>setOpen(true)}>Upload dataset</Button></Stack></Stack>
 <TextField size="small" placeholder="Search by name, type, field or well" value={search} onChange={e=>setSearch(e.target.value)} InputProps={{startAdornment:<Search size={17} style={{marginRight:8}}/>}}/>{query.isLoading&&<LinearProgress/>}{query.isError&&<Alert severity="error">Unable to load datasets.</Alert>}
 <Stack spacing={1.5}>{rows.map(d=><Paper key={d.dataset_id} variant="outlined" sx={{p:2.25,"&:hover":{borderColor:"primary.main"}}}><Stack direction={{xs:"column",md:"row"}} justifyContent="space-between" gap={2}><Box onClick={()=>setSelected(d)} sx={{cursor:"pointer",flex:1}}><Stack direction="row" gap={1} alignItems="center" flexWrap="wrap"><Typography variant="h6">{d.name}</Typography><Chip size="small" label={d.dataset_type.split("_").join(" ")} color="primary" variant="outlined"/><Chip size="small" label={d.version_id}/><Chip size="small" label={d.status}/></Stack><Typography variant="body2" color="text.secondary">{d.description||d.file_name}{d.field_name?` · ${d.field_name}`:""}{d.well_name?` / ${d.well_name}`:""}</Typography></Box><Stack direction="row" gap={2} alignItems="center" flexWrap="wrap"><Typography>{d.row_count?.toLocaleString()??"—"} rows</Typography><Typography>{bytes(d.file_size_bytes)}</Typography><Button size="small" variant="outlined" startIcon={<Download size={15}/>} onClick={()=>report.mutate(d.dataset_id)}>PDF</Button>{d.source_type==="las"&&<Button size="small" variant="outlined" startIcon={<WandSparkles size={15}/>} onClick={()=>processLas.mutate(d.dataset_id)}>Process LAS</Button>}<Button color="error" size="small" variant="outlined" startIcon={<Trash2 size={15}/>} onClick={()=>setDeleteTarget(d)}>Delete</Button></Stack></Stack></Paper>)}</Stack>
 <Dialog open={open} onClose={()=>!upload.isPending&&setOpen(false)} fullWidth maxWidth="sm"><form onSubmit={submit}><DialogTitle>Register typed dataset</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField label="Dataset name" required value={name} onChange={e=>setName(e.target.value)}/><TextField select label="Dataset type" value={datasetType} onChange={e=>setDatasetType(e.target.value)}>{TYPES.map(t=><MenuItem key={t} value={t}>{t.split("_").join(" ")}</MenuItem>)}</TextField><Stack direction={{xs:"column",sm:"row"}} gap={1}><TextField fullWidth label="Field" value={fieldName} onChange={e=>setFieldName(e.target.value)}/><TextField fullWidth label="Well" value={wellName} onChange={e=>setWellName(e.target.value)}/><TextField fullWidth label="Reservoir" value={reservoirName} onChange={e=>setReservoirName(e.target.value)}/></Stack><TextField label="Description" multiline minRows={2} value={description} onChange={e=>setDescription(e.target.value)}/><Button component="label" variant="outlined" startIcon={<FileUp size={17}/>}>{file?file.name:"Choose CSV, Parquet, LAS or Excel"}<input hidden type="file" accept=".csv,.parquet,.las,.xlsx,.xls" onChange={e=>setFile(e.target.files?.[0]??null)}/></Button>{upload.isError&&<Alert severity="error">{upload.error instanceof Error?upload.error.message:"Upload failed."}</Alert>}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" variant="contained" disabled={!name.trim()||!file||upload.isPending}>{upload.isPending?"Profiling…":"Upload"}</Button></DialogActions></form></Dialog>
 <Dialog open={Boolean(selected)} onClose={()=>setSelected(null)} fullWidth maxWidth="md"><DialogTitle>{selected?.name}</DialogTitle><DialogContent>{selected&&<Stack spacing={2}><Stack direction="row" gap={1} flexWrap="wrap"><Chip label={selected.dataset_type.split("_").join(" ")}/><Chip label={selected.version_id} color="primary"/><Chip label={selected.status} color="success"/></Stack><Divider/><Stack direction={{xs:"column",sm:"row"}} gap={3}><Stack direction="row" gap={1}><Table2 size={18}/>{selected.row_count?.toLocaleString()} rows</Stack><Stack direction="row" gap={1}><Database size={18}/>{selected.column_count} columns</Stack><Stack direction="row" gap={1}><HardDrive size={18}/>{bytes(selected.file_size_bytes)}</Stack></Stack><Typography variant="body2">SHA-256: <code>{selected.checksum_sha256}</code></Typography><Box><Typography variant="subtitle2">Lineage</Typography>{lineage.isLoading?<LinearProgress/>:<Stack direction="row" gap={1} mt={1} flexWrap="wrap"><Chip icon={<GitBranch size={14}/>} label={`Parents ${lineage.data?.parents.length??0}`}/><Chip label={`Children ${lineage.data?.children.length??0}`}/>{lineage.data?.operations.map((op,i)=><Chip key={i} size="small" variant="outlined" label={String(op.operation??"operation")}/>)}</Stack>}</Box><Box><Typography variant="subtitle2" mb={1}>Detected headers</Typography><Stack direction="row" gap={1} flexWrap="wrap">{selected.columns.map(c=><Chip key={c} label={selected.units[c]?`${c} (${selected.units[c]})`:c} size="small" variant="outlined"/>)}</Stack></Box></Stack>}</DialogContent><DialogActions><Button startIcon={<Download size={15}/>} onClick={()=>selected&&report.mutate(selected.dataset_id)}>Download PDF</Button>{selected?.source_type==="las"&&<Button startIcon={<WandSparkles size={15}/>} onClick={()=>processLas.mutate(selected.dataset_id)}>Create processed version</Button>}<Button onClick={()=>setSelected(null)}>Close</Button></DialogActions></Dialog>
 <Dialog open={Boolean(deleteTarget)} onClose={()=>setDeleteTarget(null)}><DialogTitle>Delete dataset?</DialogTitle><DialogContent><Typography>Derived children protect their parent from deletion. Remove child versions first.</Typography>{remove.isError&&<Alert severity="error" sx={{mt:2}}>{remove.error instanceof Error?remove.error.message:"Deletion failed."}</Alert>}</DialogContent><DialogActions><Button onClick={()=>setDeleteTarget(null)}>Cancel</Button><Button color="error" variant="contained" onClick={()=>deleteTarget&&remove.mutate(deleteTarget.dataset_id)}>Delete</Button></DialogActions></Dialog>
 </Stack>;
}
