import { FormEvent, useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, Box, Button, Chip, FormControl, Grid, InputLabel, LinearProgress, MenuItem, Paper, Select, Stack, TextField, Typography } from "@mui/material";
import { BrainCircuit, CheckCircle2, FlaskConical, Play, ShieldCheck, Timer } from "lucide-react";
import { createExperiment, fetchDatasets, fetchExperiments } from "./platformApi";
const algorithms=["XGBoost","Random Forest","LightGBM","CatBoost","ANN","CNN","Transformer"];
const tasks=["lithology_classification","hydrocarbon_classification","porosity_regression","permeability_regression","water_saturation_regression"];
const pretty=(v:string)=>v.replace(/_/g," ").replace(/\b\w/g,m=>m.toUpperCase());
export function TrainingWorkspacePanel(){
 const qc=useQueryClient(); const [name,setName]=useState("Niger Delta grouped-well benchmark"); const [dataset,setDataset]=useState(""); const [task,setTask]=useState(tasks[0]); const [algorithm,setAlgorithm]=useState(algorithms[0]);
 const datasets=useQuery({queryKey:["platform","datasets"],queryFn:fetchDatasets});
 const experiments=useQuery({queryKey:["platform","experiments"],queryFn:fetchExperiments,refetchInterval:(q)=>{const runs=q.state.data??[];return runs.some(r=>r.status==="queued"||r.status==="running")?1500:8000;}});
 const mutation=useMutation({mutationFn:()=>createExperiment({name,dataset_id:dataset||null,task,algorithm,validation_strategy:"grouped_by_well",parameters:{random_seed:42,explainability:"shap"}}),onSuccess:async()=>{await qc.invalidateQueries({queryKey:["platform"]});}});
 useEffect(()=>{if(!dataset&&datasets.data?.length)setDataset(datasets.data[0].dataset_id)},[datasets.data,dataset]);
 function submit(e:FormEvent){e.preventDefault();if(name.trim()&&dataset)mutation.mutate();}
 return <Stack spacing={3}>
  <Box><Stack direction="row" gap={1} alignItems="center"><BrainCircuit size={25}/><Typography variant="h5">Training Workspace</Typography></Stack><Typography color="text.secondary">Runs execute immediately on the backend and report live progress, metrics and failures.</Typography></Box>
  <Grid container spacing={2}><Grid item xs={12} lg={5}><Paper variant="outlined" sx={{p:3}}><form onSubmit={submit}><Stack spacing={2.2}><Typography variant="h6">Experiment configuration</Typography><TextField label="Experiment name" value={name} onChange={e=>setName(e.target.value)} required/><FormControl><InputLabel>Dataset</InputLabel><Select label="Dataset" value={dataset} onChange={e=>setDataset(e.target.value)}>{(datasets.data??[]).map(d=><MenuItem key={d.dataset_id} value={d.dataset_id}>{d.name} ({d.row_count??0} rows)</MenuItem>)}</Select></FormControl><FormControl><InputLabel>Task</InputLabel><Select label="Task" value={task} onChange={e=>setTask(e.target.value)}>{tasks.map(t=><MenuItem key={t} value={t}>{pretty(t)}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>Algorithm</InputLabel><Select label="Algorithm" value={algorithm} onChange={e=>setAlgorithm(e.target.value)}>{algorithms.map(a=><MenuItem key={a} value={a}>{a}</MenuItem>)}</Select></FormControl><Stack direction="row" gap={1} flexWrap="wrap"><Chip icon={<ShieldCheck size={14}/>} label="Grouped validation"/><Chip label="Seed 42"/><Chip label="Explainable"/></Stack>{mutation.isError&&<Alert severity="error">{mutation.error instanceof Error?mutation.error.message:"Training could not start."}</Alert>}{mutation.isSuccess&&<Alert severity="success">Training started. Progress is updating automatically.</Alert>}<Button type="submit" variant="contained" size="large" startIcon={<Play size={18}/>} disabled={mutation.isPending||!name.trim()||!dataset}>{mutation.isPending?"Starting…":"Create training run"}</Button></Stack></form></Paper></Grid>
  <Grid item xs={12} lg={7}><Paper variant="outlined" sx={{p:3,minHeight:430}}><Stack direction="row" justifyContent="space-between"><Typography variant="h6">Recent runs</Typography><Chip icon={<FlaskConical size={14}/>} label={`${experiments.data?.length??0} total`}/></Stack>{experiments.isLoading&&<LinearProgress sx={{mt:2}}/>}<Stack spacing={1.4} mt={2}>{(experiments.data??[]).slice(0,8).map(run=><Paper key={run.experiment_id} variant="outlined" sx={{p:2,borderColor:run.status==="running"?"primary.main":"divider"}}><Stack direction="row" justifyContent="space-between" gap={2}><Box flex={1}><Typography fontWeight={750}>{run.name}</Typography><Typography variant="body2" color="text.secondary">{pretty(run.task)} · {run.algorithm}</Typography><Stack direction="row" gap={1} mt={1} flexWrap="wrap"><Chip size="small" label={run.current_stage??run.status} color={run.status==="completed"?"success":run.status==="failed"?"error":run.status==="running"?"primary":"default"}/>{run.training_seconds!=null&&<Chip size="small" icon={<Timer size={13}/>} label={`${run.training_seconds}s`}/>} {run.status==="completed"&&<Chip size="small" icon={<CheckCircle2 size={13}/>} label={`${Object.keys(run.metrics).length} metrics`}/>}</Stack>{(run.status==="queued"||run.status==="running")&&<LinearProgress variant="determinate" value={run.progress_percent??0} sx={{mt:1.4,height:7,borderRadius:8}}/>}{run.error_message&&<Alert severity="error" sx={{mt:1}}>{run.error_message}</Alert>}{run.status==="completed"&&<Stack direction="row" gap={1} mt={1} flexWrap="wrap">{Object.entries(run.metrics).slice(0,5).map(([k,v])=><Chip size="small" variant="outlined" key={k} label={`${pretty(k)}: ${String(v)}`}/>)}</Stack>}</Box><Typography variant="caption" fontWeight={800}>{run.progress_percent??0}%</Typography></Stack></Paper>)}</Stack></Paper></Grid></Grid>
 </Stack>;
}