import {Alert,Paper,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,Typography} from "@mui/material";
import rows from "./modelReadiness039.json";
export function ModelReadinessPanel(){return <Stack spacing={2}>
 <Typography variant="h5">Model readiness</Typography>
 <Alert severity="warning">Development review snapshot, phase 038. None of these candidates is qualified for customer prediction. This is not the live model registry.</Alert>
 <Paper variant="outlined" sx={{p:2}}><Typography variant="h6">Lithology</Typography><Typography>GR-only sand/shale classification: development macro F1 0.943, versus 0.375 for the majority baseline. Requires GR in API. Depth datum remains assumed; clay is not supported. Prior test wells were excluded from this development comparison.</Typography></Paper>
 <Paper variant="outlined" sx={{p:2}}><Typography variant="h6">Porosity and permeability</Typography><Typography>Required inputs: GR (API), bulk density (g/cm3), neutron porosity (v/v), and deep resistivity (ohm.m). Laboratory fluid and stress conditions are part of the target definition. Five of six candidates beat the median on reused validation data; that is not independent qualification.</Typography>
 <TableContainer><Table size="small" aria-label="Regression readiness"><TableHead><TableRow>{["Target and condition","Development check","Validation rows","MAE","Median MAE","Unit","R squared"].map(t=><TableCell key={t}>{t}</TableCell>)}</TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.task}><TableCell>{r.task}</TableCell><TableCell>{r.passed?"Beats baseline; experimental":"Does not beat baseline"}</TableCell><TableCell>{r.validationRows}</TableCell><TableCell>{r.mae.toPrecision(4)}</TableCell><TableCell>{r.baselineMae.toPrecision(4)}</TableCell><TableCell>{r.unit}</TableCell><TableCell>{r.r2.toFixed(3)}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Paper>
 <Alert severity="info">MAE is mean absolute error in the stated unit. Negative R squared indicates poor fit relative to predicting this validation set's mean. Only 6-15 validation rows per candidate were available. The two Volve permeability targets share specimens and are not independent confirmations.</Alert>
 <Paper variant="outlined" sx={{p:2}}><Typography variant="h6">Fluid saturation</Typography><Typography>GR + density Random Forest experiments failed their historical test baseline comparison. The user-adopted 1998 date is an assumption. Of 826 RST pairs, 223 have zero oil/water values and zero corresponding volumes; their meaning is unresolved. These models are not activated. No gas model or three-phase probabilities are available.</Typography></Paper>
 <Typography>Before prediction: verify curve mapping, source units, complete finite inputs and model scope. Missing-curve models require explicit qualification; measurements must not be invented. Fresh independent parent-well evaluation is still required.</Typography>
 </Stack>}
