import {downloadTable} from "./downloadTable";
import {useEffect,useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {Alert,Button,Paper,Slider,Stack,Typography} from "@mui/material";
import {apiRequest} from "../../api/http";
import {SafePlot} from "../../components/SafePlot";
type Report={name:string;mode:string;metrics:Record<string,Record<string,unknown>>;limitations:string[];replay?:{sample:number;actual:number;prediction:number}[];history?:{date:string;actual:number;prediction:number;baseline:number;partition:string}[]};
export function PilotBenchmarkPanel({kind}:{kind:"edge"|"twin"}){
 const report=useQuery({queryKey:["pilot-benchmark",kind],queryFn:()=>apiRequest<Report>(`/pilot/benchmarks/${kind}`),retry:false});
 const [count,setCount]=useState(50);
 const [playing,setPlaying]=useState(false);
 const [exportError,setExportError]=useState("");
 useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>setCount(n=>{if(n>=(report.data?.replay?.length??1)){setPlaying(false);return n;}return n+1;}),250);return ()=>window.clearInterval(timer);},[playing,report.data]);
 const r=report.data;const points=r?.replay?.slice(0,count)??[];
 return <Paper variant="outlined" sx={{p:2}}><Stack spacing={2}><Typography variant="h5">{kind==="edge"?"Real event benchmark replay":"Measured production history"}</Typography><Alert severity="warning">Investor research demonstration. These candidates did not beat their held-out baselines and are not deployed for operational inference.</Alert><Button disabled={report.isFetching} onClick={()=>{setPlaying(false);setCount(50);void report.refetch()}}>Refresh benchmark</Button>{exportError&&<Alert severity="error">{exportError}</Alert>}{report.isError&&<Alert severity="info">{report.error.message}</Alert>}{r&&<><Typography>{r.name}</Typography><Button disabled={!(kind==="edge"?r.replay:r.history)?.length} onClick={()=>{try{downloadTable("petroedge-"+kind+"-benchmark.csv",(kind==="edge"?r.replay:r.history)??[]);setExportError("")}catch(e){setExportError(e instanceof Error?e.message:"Export failed")}}}>Download benchmark CSV</Button>{Object.entries(r.metrics).map(([part,m])=><Typography key={part}>{part}: {Object.entries(m).filter(([k])=>k!=="confusion_matrix").map(([k,v])=>`${k.replace(/_/g," ")}: ${typeof v==="number"?Number(v.toFixed(4)):v}`).join(" | ")}</Typography>)}{kind==="edge"?<><Button onClick={()=>{if(count>=(r.replay?.length??1))setCount(1);setPlaying(p=>!p)}}>{playing?"Pause replay":"Play historical replay"}</Button><Typography>Historical replay position: {count} samples. Recorded test predictions are compared with source labels; this is not a connected rig.</Typography><Slider aria-label="Replay sample count" min={1} max={r.replay?.length||1} value={Math.min(count,r.replay?.length||1)} onChange={(_,v)=>setCount(v as number)}/><SafePlot minHeight={350} data={[{x:points.map(p=>p.sample),y:points.map(p=>p.actual),name:"Recorded event label",type:"scatter",mode:"lines"},{x:points.map(p=>p.sample),y:points.map(p=>p.prediction),name:"Experimental detector",type:"scatter",mode:"markers"}]} layout={{height:350,yaxis:{title:{text:"0 normal / 1 event"}}}}/></>:<SafePlot minHeight={400} data={[{x:r.history?.map(p=>p.date),y:r.history?.map(p=>p.actual),name:"Measured oil rate",type:"scatter",mode:"lines"},{x:r.history?.map(p=>p.date),y:r.history?.map(p=>p.partition==="train"?null:p.baseline),name:"Persistence baseline",type:"scatter",mode:"lines"},{x:r.history?.map(p=>p.date),y:r.history?.map(p=>p.partition==="train"?null:p.prediction),name:"Research backtest",type:"scatter",mode:"lines"}]} layout={{height:400,yaxis:{title:{text:"Oil rate (STB/d)"}},xaxis:{title:{text:"Reporting date"}}}}/>}{r.limitations.map(x=><Typography variant="caption" key={x}>{x}</Typography>)}</>}</Stack></Paper>;
}
