import { researchPlotSamples } from "./researchPlotSamples";
import {useState} from "react";
import {useQuery,useMutation} from "@tanstack/react-query";
import {Alert,Button,Checkbox,FormControlLabel,MenuItem,Paper,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from "@mui/material";
import {apiRequest} from "../../api/http";
import {fetchDatasets} from "./platformApi";
import {SafePlot} from "../../components/SafePlot";
type Feature={name:string;unit:string;min:number;max:number};
type Model={id:string;name:string;features:Feature[];limitations:string[];validation_rows:number;validation_mae:number;unit:string};
type Result={target?:string;mode:string;model_name:string;unit:string;condition:string;predicted_rows:number;rows:number;limitations:string[];samples:{source_row:number;prediction:number|null;status:string;reasons:string[]}[]};
export function ResearchPredictionPanel(){
 const models=useQuery({queryKey:["research-models"],queryFn:()=>apiRequest<{enabled:boolean;models:Model[]}>("/training-lifecycle/research-models"),retry:false});
 const datasets=useQuery({queryKey:["platform","datasets"],queryFn:fetchDatasets});
 const [modelId,setModelId]=useState("");const [datasetId,setDatasetId]=useState("");const [mapping,setMapping]=useState<Record<string,string>>({});const [units,setUnits]=useState<Record<string,string>>({});const [ack,setAck]=useState(false);
 const model=models.data?.models.find(m=>m.id===modelId);const dataset=datasets.data?.find(d=>d.dataset_id===datasetId);
 const run=useMutation({mutationFn:()=>apiRequest<Result>("/training-lifecycle/research-predict",{method:"POST",body:JSON.stringify({model_id:modelId,dataset_id:datasetId,mapping,units,acknowledge_experimental:ack})})});
 const [permeabilityScale,setPermeabilityScale]=useState<"log"|"linear">("log");
 const isPermeability=Boolean(run.data?.target?.startsWith("permeability"));
 const logScale=isPermeability&&permeabilityScale==="log";
 const nonpositiveCount=run.data?.samples.filter(r=>r.prediction!==null&&r.prediction<=0).length??0;
 const plotSamples=researchPlotSamples(run.data?.samples??[]);
 const clear=()=>{run.reset();setAck(false)};
 const exportRun=useMutation({mutationFn:()=>apiRequest<{xlsx:string}>("/training-lifecycle/research-predict?excel=true",{method:"POST",body:JSON.stringify({model_id:modelId,dataset_id:datasetId,mapping,units,acknowledge_experimental:ack})}),onSuccess:data=>{const bytes=Uint8Array.from(atob(data.xlsx),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}));const a=document.createElement("a");a.href=url;a.download="petroedge-research-predictions.xlsx";a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}});

 return <Stack spacing={2}><Typography variant="h5">Research predictions</Typography>
 <Alert severity="warning">Administrator-only research demonstration. Not for operational decisions. Small, reused validation sets do not establish new-well accuracy. No fluid-saturation model is available here.</Alert>
 <Button disabled={models.isFetching||datasets.isFetching||run.isPending} onClick={()=>{clear();void models.refetch();void datasets.refetch()}}>Refresh research workspace</Button>
 {(models.isError||datasets.isError)&&<Alert severity="error">{models.error?.message||datasets.error?.message}</Alert>}
 {models.data&&!models.data.enabled&&<Alert severity="info">Research inference is disabled or not configured.</Alert>}
 <TextField select label="Research model" value={modelId} disabled={run.isPending} onChange={e=>{setModelId(e.target.value);setMapping({});setUnits({});clear()}}>{(models.data?.models??[]).map(m=><MenuItem value={m.id} key={m.id}>{m.name}</MenuItem>)}</TextField>
 <TextField select label="Input dataset" value={datasetId} disabled={run.isPending} onChange={e=>{setDatasetId(e.target.value);setMapping({});setUnits({});clear()}}>{(datasets.data??[]).map(d=><MenuItem value={d.dataset_id} key={d.dataset_id}>{d.name}</MenuItem>)}</TextField>
 {model&&<><Typography>Validation MAE {model.validation_mae.toPrecision(4)} {model.unit}, from {model.validation_rows} reused validation rows.</Typography>{model.limitations.map(s=><Typography key={s}>{s}</Typography>)}</>}
 {model&&dataset&&model.features.map(f=><Paper key={f.name} variant="outlined" sx={{p:2}}><Stack spacing={1}><Typography>{f.name}: training range {f.min.toPrecision(4)} to {f.max.toPrecision(4)} {f.unit}</Typography><TextField select label={`Source for ${f.name}`} value={mapping[f.name]??""} disabled={run.isPending} onChange={e=>{setMapping(v=>({...v,[f.name]:e.target.value}));clear()}}>{dataset.columns.map(c=><MenuItem key={c} value={c}>{c}</MenuItem>)}</TextField><TextField label={`Source unit for ${f.name}`} placeholder={f.unit} value={units[f.name]??""} disabled={run.isPending} onChange={e=>{setUnits(v=>({...v,[f.name]:e.target.value}));clear()}}/></Stack></Paper>)}
 <Typography>Full-well research runs support up to 100,000 rows and 50 MB, with batch prediction. Declare the actual source units. Supported forms: API/GAPI; g/cm3, G/C3, G/CC or kg/m3; v/v, FRAC, PU or %; ohm.m, OHMM or OHM-M. Existing dataset unit declarations must match. Missing, nonfinite, known null and training-range violations are withheld; inputs are never imputed.</Typography>
 <FormControlLabel control={<Checkbox checked={ack} disabled={run.isPending} onChange={e=>setAck(e.target.checked)}/>} label="I understand the experimental scope and have reviewed the source mappings and units"/>
 <Button variant="contained" disabled={!ack||!model||!dataset||run.isPending||model.features.some(f=>!mapping[f.name]||!units[f.name])} onClick={()=>run.mutate()}>{run.isPending?"Running research prediction...":"Run research prediction"}</Button>
 {run.isError&&<Alert severity="error">{run.error.message}</Alert>}
 {run.data&&<Paper variant="outlined" sx={{p:2}}><Stack spacing={2}><Alert severity="warning">Research output: {run.data.model_name}. {run.data.predicted_rows} of {run.data.rows} rows predicted; remaining rows withheld. Unit: {run.data.unit}. Condition: {run.data.condition}.</Alert><Button disabled={exportRun.isPending} onClick={()=>exportRun.mutate()}>Download research results Excel</Button>{exportRun.isError&&<Alert severity="error">{exportRun.error.message}</Alert>}<Typography variant="caption">Excel export rechecks the source and model and repeats this research run, including all withheld rows and provenance.</Typography>{isPermeability&&<TextField select label="Permeability axis scale" value={permeabilityScale} onChange={e=>setPermeabilityScale(e.target.value as "log"|"linear")}><MenuItem value="log">Logarithmic (base 10)</MenuItem><MenuItem value="linear">Linear</MenuItem></TextField>}{logScale&&<Typography variant="body2">Logarithmic permeability axis: each major division represents a tenfold change. Hover to read the original value in {run.data.unit}.</Typography>}{logScale&&nonpositiveCount>0&&<Alert severity="info">{nonpositiveCount} zero or negative results cannot appear on a logarithmic axis. Switch to linear to view them; their original values remain in the table and Excel export.</Alert>}<SafePlot data={[{x:plotSamples.map(r=>r.source_row),y:plotSamples.map(r=>logScale&&r.prediction!==null&&r.prediction<=0?null:r.prediction),hovertemplate:`Source row: %{x}<br>Prediction: %{y:.6g} ${run.data.unit}<extra></extra>`,type:"scatter",mode:"markers",name:"Experimental prediction"}]} layout={{height:350,xaxis:{title:{text:"Source row (zero-based; not depth)"}},yaxis:{title:{text:isPermeability?`Permeability (${run.data.unit})${logScale?" - log scale":""}`:run.data.unit},type:logScale?"log":"linear",...(logScale?{dtick:1,exponentformat:"none",minor:{showgrid:true,ticks:"inside"}}:{}),automargin:true}}} minHeight={350}/><Typography>Plot displays up to 2,000 evenly spaced source rows. First 50 rows shown below. Download includes every processed row, reasons, input mappings, model/dataset hashes and limitations.</Typography><Table size="small"><TableHead><TableRow><TableCell>Source row</TableCell><TableCell>Prediction</TableCell><TableCell>Status / reason</TableCell></TableRow></TableHead><TableBody>{run.data.samples.slice(0,50).map(r=><TableRow key={r.source_row}><TableCell>{r.source_row}</TableCell><TableCell>{r.prediction===null?"Withheld":r.prediction.toPrecision(4)}</TableCell><TableCell>{r.reasons.join("; ")||r.status}</TableCell></TableRow>)}</TableBody></Table></Stack></Paper>}
 </Stack>
}
